ID-22: implementation of random init, layer and base optimizer
SPbuMinecraft/GraphicalEditorForNN pull request #16
Opened 2023-10-15 16:55 UTC by Maxon081102

https://ru.yougile.com/team/b400e1850fe9/#chat:327695f7aa6c

2023-10-16 04:43 UTC, Artem-Goldenberg reviewed
Влей мейн, а то так несовсем понятно вообще как это в итоге будет

2023-10-16 04:43 UTC, Artem-Goldenberg commented on server/Blob.h
> +    float* data;
Да за што паблик?

2023-10-16 04:43 UTC, Artem-Goldenberg commented on server/Layer.h
> +#include "Tensor.h"
В Tensor.h уже включается Operation.h, ууу лишние инклюды не люблю

2023-10-16 04:43 UTC, Artem-Goldenberg commented on server/Layer.h
> +
А почему все паблик? Ну реально,  garbageTensors тогда уж хотя бы private сделай

2023-10-16 04:43 UTC, Artem-Goldenberg commented on server/Optimizer.cpp
> +        params[i].get().output.value() -= lr * params[i].get().gradient.value();
ну так вот, с optional можно написать `*b.output -= lr * *b.gradient` если `auto b = params[i].get()`

2023-10-16 04:43 UTC, Artem-Goldenberg commented on server/Optimizer.h
> +    OptimizerBase(const float lr) : lr(lr), params() {};
сюда если что нет смысла const float передавать, он и так по значению передается

2023-10-16 04:43 UTC, Artem-Goldenberg commented on server/Tensor.cpp
> +    gradient = Blob {output.value().rows, output.value().cols};
`output->rows, output->cols`

2023-10-16 04:43 UTC, Artem-Goldenberg commented on server/Tensor.cpp
> +    gradient = Blob {data.rows, data.cols};
А зачем output тогда вообще optional если у нас уже есть флаг этот что он nil?

2023-10-16 04:43 UTC, Artem-Goldenberg commented on server/Tensor.cpp
> +}
Че то я не понял, это я дурак или как это вообще гкомпилится, ты же тензор в итоге не возвращаешь

2023-10-16 20:34 UTC, lpetrov02 requested changes
Я там побухтел, соре.. В основном по кодстайлу, а из содержательного - всё классно

2023-10-16 20:34 UTC, lpetrov02 commented on server/core/RandomInit.cpp
> +    for (int i = 0; i < size; i++) data[i] = randomNumber();
Ну такаааая же себе тема писать for в одну строчку))

2023-10-16 20:34 UTC, lpetrov02 commented on server/core/Blob.cpp
> +Blob::Blob(size_t rows, size_t cols, bool randomInit, RandomObject* object): rows(rows), cols(cols) {
Кажется, указатель на RandomObject можно сделать константным

2023-10-16 20:34 UTC, lpetrov02 commented on server/core/Blob.cpp
> +    else object->simpleInit(this->data, rows * cols);
Мы не обсуждали кодстайл, но я бы такое запретил)
Надо будет обсудить ~~и запретить~~

2023-10-16 20:34 UTC, lpetrov02 commented on server/core/Blob.cpp
>  float Blob::at(size_t i, size_t j) const {
Кажется, *at* обычно проверяет границы - и это его основное отличие от operator[]
Хотя тут удобство ещё и в меньшем количестве скобок, это понимаю. Но я бы добавил проверки и исключения.

2023-10-16 20:34 UTC, lpetrov02 commented on server/core/Blob.cpp
>      if (this == &t) return *this;
if в 1 строчку

2023-10-16 20:34 UTC, lpetrov02 commented on server/core/Blob.cpp
>  using namespace std;
Может всё-таки не надо?)
Ну то есть я не знаю, вряд ли будут совпадения имён, но всегда и везде так говорят ни в коем случае не делать, на всякий

2023-10-16 20:34 UTC, lpetrov02 commented on server/core/Blob.cpp
> +    else object->simpleInit(this->data, rows * cols);
Я там дальше ещё в паре мест написал, но оно так много где, так что не везде откомментил

2023-10-16 20:34 UTC, lpetrov02 commented on server/core/Blob.h
> +    float* getData() const;
Это не столько замечание, сколько вопрос: тут нет опасности, что мы возьмём указатель, потом блоб умрёт, ни данные удалятся?

2023-10-16 20:34 UTC, lpetrov02 commented on server/core/Blob.cpp
> +    if (!randomInit || object == nullptr) clear();
Не избыточен ли тут флаг randomInit?

2023-10-16 20:34 UTC, lpetrov02 commented on server/core/Layer.cpp
> +    W (dataInit((size_t) params["h"], (size_t) params["w"], randomInit)),
Парсинг - это уже моя таска, так что сам перепишу, но лучше, конечно, static_cast, он крутой

2023-10-16 20:34 UTC, lpetrov02 commented on server/core/Layer.h
> +public:
public, sure?

2023-10-16 20:34 UTC, lpetrov02 commented on server/core/Blob.cpp
> +    memcpy(this->data, t.data, sizeof(float) * t.cols * t.rows);
Мы не хотим уметь присваивать блобы других размерностей?

2023-10-16 20:34 UTC, lpetrov02 commented on server/core/Operation.cpp
> +    res[0].get() += grad;
Наврное, это не важно, но имя метода `get()` как будто бы подразуевает *read-only*

2023-10-16 20:34 UTC, lpetrov02 commented on server/core/Operation.cpp
> +    float number = grad[0][0] * (((float) 1) / (args[0].get().rows * args[0].get().cols));
`1.0f` вроде бы можно вместо `(float) 1`

2023-10-16 20:34 UTC, lpetrov02 commented on server/core/Tensor.cpp
> +    for (auto p: parents) grads.push_back(p.get().gradient.value());
for в одну строчку

2023-10-16 20:34 UTC, lpetrov02 commented on server/core/Tensor.cpp
> +    this->gradient = other.gradient;
А зачем явно `this->operation = ...` писать вместо `operation = ...`?

2023-10-17 07:24 UTC, Maxon081102 commented on server/core/RandomInit.cpp
> +    for (int i = 0; i < size; i++) data[i] = randomNumber();
не согласен, for маленький и не несет в себе ничего сложного, а чем меньше строк, тем лучше

2023-10-17 07:27 UTC, Maxon081102 commented on server/core/Blob.cpp
> +    else object->simpleInit(this->data, rows * cols);
ну, это не вылезает за 80 символов + тут нет никакой сложной логики, зачем из двух строк делать 4?

2023-10-17 07:27 UTC, Maxon081102 commented on server/core/Blob.cpp
>  float Blob::at(size_t i, size_t j) const {
Это не я писал

2023-10-17 07:28 UTC, Maxon081102 commented on server/core/Blob.cpp
>      if (this == &t) return *this;
и это не я писал, но мне нравится, как выглядит

2023-10-17 07:28 UTC, Maxon081102 commented on server/core/Blob.cpp
>  using namespace std;
это не я писал

2023-10-17 07:30 UTC, Maxon081102 commented on server/core/Blob.h
> +    float* getData() const;
Blob сейчас так не работает(это нужно только для копии, но я понял, как можно избавиться от этого)

2023-10-17 07:30 UTC, lpetrov02 commented on server/core/Blob.cpp
> +    else object->simpleInit(this->data, rows * cols);
Ладно ладно, я не буду нудить, мб это лично мне не нравится, тогда ничего страшного

2023-10-17 07:30 UTC, Maxon081102 commented on server/core/Blob.cpp
> +    if (!randomInit || object == nullptr) clear();
да, согласен, надо убрать

2023-10-17 07:31 UTC, Maxon081102 commented on server/core/Layer.cpp
> +    W (dataInit((size_t) params["h"], (size_t) params["w"], randomInit)),
я поэтому и не парился)

2023-10-17 07:32 UTC, Maxon081102 commented on server/core/Layer.h
> +public:
аааа, там в старой версии нужно было, уберу

2023-10-17 07:33 UTC, Maxon081102 commented on server/core/Blob.cpp
> +    memcpy(this->data, t.data, sizeof(float) * t.cols * t.rows);
надо что-то сделать с blob-ом, тк он пока не удовлетворяет нашим требованиям (которые миллион раз менялись), но уже не в этом пр

2023-10-17 07:34 UTC, Maxon081102 commented on server/core/Operation.cpp
> +    res[0].get() += grad;
это из-за Ref, без этого не получится

2023-10-17 07:34 UTC, Maxon081102 commented on server/core/Operation.cpp
> +    float number = grad[0][0] * (((float) 1) / (args[0].get().rows * args[0].get().cols));
поменяю

2023-10-17 07:34 UTC, Maxon081102 commented on server/core/Tensor.cpp
> +    this->gradient = other.gradient;
согласен, поменяю

2023-10-17 07:35 UTC, lpetrov02 commented on server/core/Operation.cpp
> +    res[0].get() += grad;
Пон, в целом норм да

2023-10-17 09:09 UTC, Artem-Goldenberg commented on server/core/Blob.cpp
>      if (this == &t) return *this;
ХАхаха да блин Леня иногда в одну строчку можно писать, за это тебя не покарают, разве что форматер покарает но к счастью на ++ у нас его нет, он убивает всю креативность

2023-10-17 09:31 UTC, Artem-Goldenberg commented on server/core/Tensor.cpp
> +    this->gradient = other.gradient;
чисто свое видение напишу, когда я присваиваю что-то я пишу `this->...=` а когда я просто использую я пишу без this чтобы быстро видеть все места где я меняю какую-то переменную, но это просто мой стиль

2023-10-18 18:06 UTC, Maxon081102 commented on server/core/Blob.h
> +    float* getData() const;
решил не менять, тк откажемся от этого скоро

2023-10-18 18:14 UTC, Maxon081102 commented on server/core/Layer.h
> +public:
от этого не отказаться

2023-10-18 19:39 UTC, Artem-Goldenberg approved these changes
Короче ладно, я че-то начал тут расписывать, потом понял что все равно мне это рано или поздно мержить придется так что зачем, главное я проверил реально работает, у тебя И вообще классно угадывается под 0, так что зачет, Макс, зачет

2023-10-18 19:39 UTC, Artem-Goldenberg commented on server/core/Tensor.cpp
> +    this->gradient = other.gradient;
Так Макс давай-ка это.. все таки сделай 
```
Tensor& Tensor::operator=(const Tensor & other) {
...
return *this;
}
```
https://stackoverflow.com/questions/3402178/omitting-return-statement-in-c
А то написано что случится undefined behaviour, это почти всегда значит что если работает значит пофиг, работать будет. Но все таки верни this ну чтобы уж тоочно

2023-10-18 20:45 UTC, lpetrov02 approved these changes

2023-10-19 18:01 UTC, merged