ID-32: db for layers and their connections
SPbuMinecraft/GraphicalEditorForNN pull request #2
Opened 2023-09-28 18:04 UTC by MaxVorosh

[ID-34](https://ru.yougile.com/team/b400e1850fe9/#chat:8f44f8dc082e)

2023-09-28 21:13 UTC, lpetrov02 requested changes
В целом всё хорошо. Накидал комментов, что сразу в глаза бросилось, завтра тщательнее посмотрю

2023-09-28 21:13 UTC, lpetrov02 commented on db/app.py
> +    in_features = db.Column(db.Integer, nullable=False)
Так как в разных слоях могут быть разные (совершенно разные) наборы параметров, лучше все параметры слоя хранить в одном столбце типа String.
Но пока и так норм, если ограничиться линейным)

2023-09-28 21:13 UTC, lpetrov02 commented on db/app.py
> +    def check_dimencions(self, layer_from, layer_to):
через s

2023-09-28 21:13 UTC, lpetrov02 commented on db/app.py
> +
структуру бд я бы отдельно обсудил на самом деле
если так работает, то класс, пока можно оставить, но, есдинственное, нам нужно ещё id модели получить, потому что у юзера может быть несколько проектов

2023-09-28 21:13 UTC, lpetrov02 commented on db/app.py
> +        with app.app_context():
если тут у нас будет id модели, то можно сильно не править, а просто доставать тут всё connections по этому айдишнику

2023-09-29 13:55 UTC, lpetrov02 commented on db/app.py
> +
Вроде норм)

2023-09-29 13:58 UTC, lpetrov02 approved these changes
Кажется, всё хоошо

2023-10-01 18:44 UTC, heartmarshall reviewed
Всё ок, обсудили  в тг

2023-10-01 18:45 UTC, heartmarshall approved these changes

2023-10-01 20:15 UTC, merged