Id-67: on-line check if graph is acyclic
SPbuMinecraft/GraphicalEditorForNN pull request #21
Opened 2023-10-17 13:38 UTC by MaxVorosh

[Id-67](https://ru.yougile.com/team/b400e1850fe9/#chat:978de136d4f5)

2023-10-17 15:15 UTC, lpetrov02 requested changes
Ну смотри, на счёт самого алгоритма - пока ладно, можно наверное вынести в отдельный тикет (или тыкни меня, где я не прав, это тоже норм будет), но `list` для очереди не используй плиз (я проверил, пишут, `list.pop(0)` - это `O(n)`. `Deque` - хорошее решение. Или `Queue`

2023-10-17 15:15 UTC, lpetrov02 commented on py_server/mlcraft/db.py
> +from .utils import LayersConnectionStatus, DeleteStatus, parse_parameters, is_path_exist
maybe `check_path_exists`? ну это чисто с точки зрения английского языка придирка)

2023-10-17 15:15 UTC, lpetrov02 commented on py_server/mlcraft/utils.py
>          layers_queue.pop(0)
Я точно не знаю, как это релизовано, но есть ощущение, что `pop(0)` для list может работать за `O(n)`. Предлагаю уточнить этот момент или использовать `deque` (`from collections import deque`)

2023-10-17 15:15 UTC, lpetrov02 commented on py_server/mlcraft/db.py
> +from .utils import LayersConnectionStatus, DeleteStatus, parse_parameters, is_path_exist
Лучше даже `check_paths_exist`)

2023-10-17 15:15 UTC, lpetrov02 commented on py_server/mlcraft/utils.py
>          for layer_to in edges[layer]:
Да, я вижу, что это раньше уже было влито, но:
сильно лаконичнее будет написать одной строчкой `for layer_to in edges.get(layer, []):` - там конечно, если что, создастся пустой `list`, но помимо этого - вроде симпатичнее)
(впрочем, не настаиваю)

2023-10-17 15:15 UTC, lpetrov02 commented on py_server/mlcraft/utils.py
> +def is_path_exist(start_ids: list, stop_ids: list, model_dict: dict):
Насколько я понял, функция чекает, нет ли путей от **output** к **data**, но циклы можнор намутить и внутри модели.
Подробно не вникал, но как будто бы тут **DFS** больше в тему

2023-10-17 15:15 UTC, lpetrov02 commented on py_server/mlcraft/utils.py
> +            params_dict[param_name] = param_value  # type: ignore
Если сделать просто поиск направленных циклов в графе, то достаточно возвращать `bool` (это правда?)

2023-10-17 17:03 UTC, MaxVorosh commented on py_server/mlcraft/utils.py
> +def is_path_exist(start_ids: list, stop_ids: list, model_dict: dict):
Эта функция вызывается каждый раз при добавлении соединения. Я просто не позволяю добавить соединение, которое создаёт цикл. Поэтому граф в любой момент времени ацикличен. А при отправке на train нужно лишь проверить достижимость output из data.
А насчёт DFS, можно было и его написать. Но он решает ту же задачу, а мне удобнее было написать BFS (по структуре кода)

2023-10-17 17:07 UTC, MaxVorosh commented on py_server/mlcraft/utils.py
>          layers_queue.pop(0)
Мне однозначно говорили в лагере по спортпроге, что в питоне можно list использовать как stack, deque и queue. Но возможно они имели в виду функционал. Поправлю

2023-10-17 17:09 UTC, MaxVorosh commented on py_server/mlcraft/utils.py
> +            params_dict[param_name] = param_value  # type: ignore
Не очень понял, про какой метод идёт речь

2023-10-17 17:22 UTC, lpetrov02 commented on py_server/mlcraft/utils.py
> +def is_path_exist(start_ids: list, stop_ids: list, model_dict: dict):
Ладно, вроде логично

2023-10-17 17:28 UTC, lpetrov02 commented on py_server/mlcraft/utils.py
> +            params_dict[param_name] = param_value  # type: ignore
Я имею в виду как раз функцию, внутри которой bfs реализован
Имел в виду, нельзя ли спрятать всё внутрь функции так, чтобы вовращать `bool`?

2023-10-17 18:01 UTC, MaxVorosh commented on py_server/mlcraft/utils.py
> +            params_dict[param_name] = param_value  # type: ignore
Я же и так bool возвращаю. Делаю all от массива. Или я туплю?

2023-10-17 19:39 UTC, Artem-Goldenberg approved these changes
Все ок, сделай там только то что Леня просит

2023-10-19 18:35 UTC, lpetrov02 approved these changes

2023-10-19 18:35 UTC, lpetrov02 commented on py_server/mlcraft/utils.py
> +            params_dict[param_name] = param_value  # type: ignore
Так ладно, это вроде не принципиально, потом обсудим, если вдруг будет мешать, а пока го оставим

2023-10-19 18:36 UTC, merged