Adds json parser and graph builder
SPbuMinecraft/GraphicalEditorForNN pull request #27
Opened 2023-10-24 06:24 UTC by lpetrov02

## Graph parser  
- Nomal Layers initialization, without any maps  
- Using heap for storing Layers
- Models are able to train

2023-10-24 14:56 UTC, Artem-Goldenberg commented on server/core/Layer.h
>  public:
Блин, ну давайте договоримся про это нижнее подчеркивание, а то так у нас будет наплывами, кто фиксит код, тот там все и меняет по своему стилю, а потом это опять меняется, может Layer оставим без нижних подчеркиваний, а при этом Parser и GraphBuilder будут использовать нижние подчеркивания потому что они как бы из отдельной библиотеки?

2023-10-24 16:02 UTC, Artem-Goldenberg commented on server/api/server.cpp
А то есть ты не делал предикт сам? То есть сейчас парсится и работает только train?

2023-10-24 16:02 UTC, Artem-Goldenberg commented on server/core/Layer.cpp
> +static Blob dataInit(size_t h, size_t w, RandomObject* const randomInit) {
Давайте const писать сначала: `const RandomObject*`

2023-10-24 16:02 UTC, Artem-Goldenberg commented on server/core/Layer.cpp
> +}
а почему не через дефолтный аргумент, типа
```
dataInit(size_t h, size_t w, RandomObject* const randomInit = nullptr)
```

2023-10-24 16:02 UTC, Artem-Goldenberg commented on server/core/Layer.cpp
> +    result_ = Tensor(Blob{height_, width_, values.data()});
Тут можно опускать имя Blob: `Tensor({height_, width_, values.data()});`

2023-10-24 16:02 UTC, Artem-Goldenberg commented on server/api/Parser.h
> +};
Так а если уже структуру такую заводим, то давай чтоыб `LinearLayer` принимал в ините ее. Так будет удобнее не надо будет в нее запаковывать а потом распаковывать. 
Ну или альтернативно можно чтобы функция `ParseLinear` сразу же возвращала линейный слой

2023-10-24 16:02 UTC, Artem-Goldenberg commented on server/api/Parser.cpp
> +    }
просто вопрос, а вот эти все параметры `bias` `device` они где то написаны. Кто то вообще знает что их можно передовать? Если нет, то наверное надо это все стандартизировать как то

2023-10-24 16:02 UTC, Artem-Goldenberg commented on server/api/GraphBuilder.h
> +    const std::vector<int>& getLastTrainIds() const;
Если эта штука используется только чтобы получить ссылку на слои, то можно сделать метод который сразу будет возвращать ссылки на слои (пока можно сделать одну ссылку на слой)

2023-10-24 16:02 UTC, Artem-Goldenberg commented on server/api/Parser.cpp
> +        throw std::invalid_argument("Argument " + field + " is required for this type of Layer");
Удобный метод, но сообщение об ошибке не всегда актуально. Например иногда вместо `layer` передается json всех модели. Поэтому я бы изменил на что то вроде `No field <filed> found in <json>`
Я так переживаю по этому поводу потому что скорее всего это сообщение мы будет отправлять на сервер в случае неудачного запроса, ну и удобно когда сообщение корректное чтобы баги быстро искать

2023-10-24 16:02 UTC, Artem-Goldenberg commented on server/api/GraphBuilder.cpp
> +        }
По моему в с++ если обратится к map а там нету значения, он автоматически запустит дефолтный конструктор значения, так что этого можно не делать

2023-10-24 16:02 UTC, Artem-Goldenberg commented on server/api/GraphBuilder.cpp
> +        }
уфф как же я долго парсил что тут за условие в парсерер ахаха, ну вообщем это, у нас же все приходит к слою у которого тип Output, а я его здесь что то вообще не вижу, здесь наверное надо как раз на этот тип проверять

2023-10-24 16:35 UTC, Maxon081102 commented on server/core/Layer.cpp
> +static Blob dataInit(size_t h, size_t w, RandomObject* const randomInit) {
нет, тогда смысл другой, надо именно так RandomObject* const randomInit

2023-10-24 16:38 UTC, Maxon081102 commented on server/api/Parser.cpp
> +    }
bias нужно добавить, как параметр на фронте, а device нам не нужен, уже обсуждали

2023-10-24 17:46 UTC, Artem-Goldenberg commented on server/core/Layer.cpp
> +static Blob dataInit(size_t h, size_t w, RandomObject* const randomInit) {
аа ну да я забыл про смысл, но смысл правильный в варианте const сначала 
Потому что зачем тебе указатель который ты не можешь переставить?
Тебе нужно гарантировать тому кто вызывает функцию, что по указателю который он передал ничего не будет записано

2023-10-24 17:48 UTC, Artem-Goldenberg commented on server/api/Parser.cpp
> +    }
окей, ну вот надо это где-то записывать все

2023-10-24 20:46 UTC, lpetrov02 commented on server/api/server.cpp
Добавил predict, но с глоальными переменными мутно  
Предлагаю оставить до лучших времён (когда появятся сессии)

2023-10-24 20:51 UTC, lpetrov02 commented on server/core/Layer.h
>  public:
Ок, откатил как было

2023-10-24 20:57 UTC, lpetrov02 commented on server/core/Layer.cpp
> +static Blob dataInit(size_t h, size_t w, RandomObject* const randomInit) {
Мне константность указателя кажется не очень нужно, но у самого объекта вызывается неконстантный `simpleInit`, насколько я понимаю, так что есть проблемка  
Пока оставляю

2023-10-24 20:59 UTC, lpetrov02 commented on server/core/Layer.cpp
> +}
реально

2023-10-24 21:00 UTC, lpetrov02 commented on server/api/Parser.h
> +};
Чтобы функция сразу слой возвращала - неудобно, так как есть ещё параметры, которые не для слоя, а для графа  
А так в целом да)

2023-10-24 21:10 UTC, lpetrov02 commented on server/api/Parser.cpp
> +    }
Пока параметры взяты тупо с торча  
Согласен что гпушки мы вряд ли успеем подтянуть, так что да))  
Думаю, когда на фронте появятся - тогда уберём мусор

2023-10-24 21:12 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +        }
На данный момент такого типа нет  
Но если добавить, то да, именно оно здесь и будет)  
А пока эвристики

2023-10-24 21:13 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +        }
Не уверен, что это так сработает, если сразу делать `push_back`

2023-10-24 21:15 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +        }
Ладно, работает

2023-10-24 21:45 UTC, Artem-Goldenberg commented on server/core/Layer.cpp
> +static Blob dataInit(size_t h, size_t w, RandomObject* const randomInit) {
А блин, там тоже вызывается, ну тогда убери просто этот const вообще

2023-10-24 21:47 UTC, Artem-Goldenberg commented on server/api/GraphBuilder.cpp
> +        }
Стоп, а разве фронтент не присылает Output сейчас?

2023-10-25 09:21 UTC, lpetrov02 commented on server/core/Layer.cpp
> +static Blob dataInit(size_t h, size_t w, RandomObject* const randomInit) {
Да, это можно, поправлю

2023-10-25 09:23 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +        }
Ну мы полный цикл не запускали пока, так что не знаю)  
Но знаю, что Ваня хочет сделать, если уже не сделал  
А я сам не уверен на счёт `Output`, потому что он как будто бы бестолковый: выход при предикте - это `result_` у верхнего слоя, отвечающего за предсказание, а выход при трейне - это просто лосс

2023-10-26 01:32 UTC, Artem-Goldenberg requested changes
Ну попробуй сделать с двойным указателем как я написал, мб заработает

2023-10-26 01:32 UTC, Artem-Goldenberg commented on server/api/server.cpp
> +    graph = new Graph(json, &initObject, SGD);
Так ало, у тебя же здесь указатель по значению передается, то что ты его присваиваешь на new Graph, он не возвращается, нужно передавать `Graph**`

2023-10-26 01:32 UTC, Artem-Goldenberg commented on server/api/server.cpp
>          float x;
ну x уже не нужен, тут помощнее штуки пошли)

2023-10-26 01:32 UTC, Artem-Goldenberg commented on server/api/GraphBuilder.cpp
> +        ParseInputData(data[key]["values"], values);
Окей я опять запутался какой у нас в итоге формат в предикате, там же не было values 
```
"0": { 
  "parameters": {...}
  "values": [...]
}
```
Такой? Если такой, то зачем там параметры, мы же и так id уже знаем, значит знаем и параметры. 
Ну и раз параметры не нужны то "values" можно тоже убрать и сделать 
```
"0": [...]
```

2023-10-26 01:32 UTC, Artem-Goldenberg commented on server/api/GraphBuilder.cpp
> +    }
По моему инит блоба делает то же самое

2023-10-26 16:51 UTC, lpetrov02 commented on server/api/server.cpp
> +    graph = new Graph(json, &initObject, SGD);
Оу май

2023-10-26 16:52 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +        ParseInputData(data[key]["values"], values);
параметры нужны, если мы хотим предиктиться на данных другого размера

2023-10-26 17:02 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +    }
Вроде да, но тут важно переписать данные в ту же память

2023-10-26 19:39 UTC, Artem-Goldenberg commented on server/api/GraphBuilder.cpp
> +    }
output можно менять, это просто optional

2023-10-26 19:41 UTC, Artem-Goldenberg commented on server/api/GraphBuilder.cpp
> +        ParseInputData(data[key]["values"], values);
нут хз вы это уже обсудили?

2023-11-01 14:19 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +        ParseInputData(data[key]["values"], values);
Обсудили на созвоне, решили вопрос

2023-11-01 14:19 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +    }
да, сейчас уже так и работает

2023-11-01 14:21 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +        }
Теперь есть Output, всё стало красивее

2023-11-01 19:08 UTC, Maxon081102 requested changes

2023-11-01 19:08 UTC, Maxon081102 commented on server/core/Layer.cpp
не надо init b, если он не нужен

2023-11-01 19:08 UTC, Maxon081102 commented on server/core/Layer.h
>  public:
согласен, менять чужой код, когда мы не обсуждали code style - плохо
+ мое мнение про _: падает читабельность и неудобнее писать становится

2023-11-01 19:08 UTC, Maxon081102 commented on server/core/Layer.cpp
> +    }
с b надо не так, нужно его сделать optional и заполнять, если он есть, но ты можешь оставить это на меня

2023-11-01 19:08 UTC, Maxon081102 commented on server/core/Operation.cpp
> +
зачем?

2023-11-01 19:08 UTC, Maxon081102 commented on server/core/Tensor.h
> +    Tensor(const Operation& operation, const std::vector<TensorRef>& parents, bool noGrad = false);
зачем? это нигде не используется

2023-11-01 19:08 UTC, Maxon081102 commented on server/api/Parser.cpp
> +    }
cpu нужно убрать

2023-11-01 19:08 UTC, Maxon081102 commented on server/core/Layer.cpp
>      pipeline.reserve(2);
и random init тогда уж надо убрать

2023-11-01 19:16 UTC, Artem-Goldenberg commented on server/api/GraphBuilder.cpp
> +        layer->result.value().output.value() = values.data();
`layer->result->output = Blob {1, 2, values.data()}`
Ну первая размеренность 1 всегда пока что тк предиктим одну штуку
А 2 - это размеренность фичей самих

2023-11-01 19:35 UTC, lpetrov02 commented on server/core/Operation.cpp
> +
Потому что Output - это фиктивный слой (который все очень хотят, но я в целом тоже уже согласен, что с ним красивее). И он просто копирует данные из посленего вычислительного слоя модели. При этом при каждом `forward` должен обновляться. Для этого нужна тождественная операция, которая прокидывает значение без изменений. Если я правильно понял `NoOp`, она так не умеет, она ничего не прокидывает а просто делает ничего

2023-11-01 19:37 UTC, lpetrov02 commented on server/core/Tensor.h
> +    Tensor(const Operation& operation, const std::vector<TensorRef>& parents, bool noGrad = false);
Используется
Опять же, для этого `Output`. В него идёт ребро из последнего вычислительного слоя, и когда мы создаём тензор, счётчик детей у этого самого последнего вычислительного увеличивается. Как следствие, слой ждёт на одного ребёнка больше при подсчёте градиента. А так как `Output` вообще не участвует в обучении, так и не дождётся, и всё пойдёт криво

2023-11-01 19:38 UTC, lpetrov02 commented on server/api/Parser.cpp
> +    }
Можно)  
Но чем оно так принципиально тебе не нравится? Да, вряд ли мы до этого дойдём, но это как задел на некое "будущее"

2023-11-01 19:38 UTC, lpetrov02 commented on server/core/Layer.cpp
>      pipeline.reserve(2);
Тут не поспоришь

2023-11-01 19:40 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +        layer->result.value().output.value() = values.data();
ну нет мы вообще не одну штуку предиктим  
но в целом поинт ясен, щас проверю работоспособность

2023-11-01 19:43 UTC, Artem-Goldenberg commented on server/api/GraphBuilder.cpp
> +        layer->result.value().output.value() = values.data();
всмсле не одну? одну пока, и я думаю так будет еще долго

2023-11-01 19:45 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +        layer->result.value().output.value() = values.data();
а зачем одну, если можно не одну?

2023-11-01 19:46 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +        layer->result.value().output.value() = values.data();
если это ограничение с фронта, то пусти присылают одну  
1 - это частный случай N

2023-11-01 19:48 UTC, Artem-Goldenberg commented on server/core/Tensor.h
> +    Tensor(const Operation& operation, const std::vector<TensorRef>& parents, bool noGrad = false);
Так давай теперь выставлять градиент 1 не последнему вычислительному, а Output

2023-11-01 19:48 UTC, Artem-Goldenberg commented on server/core/Operation.cpp
> +
Ну согласен да, это не тоже самое

2023-11-01 19:49 UTC, lpetrov02 commented on server/core/Tensor.h
> +    Tensor(const Operation& operation, const std::vector<TensorRef>& parents, bool noGrad = false);
Не понял, можешь плиз чуть подробнее?

2023-11-01 19:51 UTC, Artem-Goldenberg commented on server/api/GraphBuilder.cpp
> +        layer->result.value().output.value() = values.data();
Да это понятно, но из-за этого усложняется код, пусть тебе кажется что не сильно, но он все равно усложняется. И вот много моментов таких мелких где вы почему-то сразу же для самого общего случая все делаете, когда можно спокойно сейчас сделать легче, а потом уже если реально надо будет, то добавить новое. Код - не бетон как говорится ахах

2023-11-01 19:58 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +        layer->result.value().output.value() = values.data();
ну всё равно не согласен  
размерность здесь должна быть совершенно бесплатно  
кстати, для 1 даже сложнее, сейчас что-то не перестраивается, и значений в предикте всегда 4  
так что 1 и N - одинаково по сложности. И я сделаю N

2023-11-01 19:58 UTC, lpetrov02 commented on server/api/Parser.cpp
> +    }
Ладно пофиг уберу, больше его обсуждаем, того не стоит)

2023-11-01 20:00 UTC, Artem-Goldenberg commented on server/api/GraphBuilder.cpp
> +        layer->result.value().output.value() = values.data();
Так тебе для этого надо формат json для предикта усложнять, вместо просто чисел нужно передавать еще какая размерность там и тд,
Всмысле, что значит, что-то не перестраивается? Как значений может быть 4 если мы будем 1 передавать?

2023-11-01 20:58 UTC, lpetrov02 commented on server/core/Layer.cpp
> +    }
Поправил (мб не слишком изящно, но кмк норм)

2023-11-01 21:37 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +        layer->result.value().output.value() = values.data();
Так всё, я пофиксил багу  
Можно передавать сколько угодно, в том числе одну штуку)

2023-11-01 22:11 UTC, Artem-Goldenberg commented on server/api/GraphBuilder.cpp
> +        layer->result.value().output.emplace(Blob{values.size() / width, width, values.data()});
1. почему равно не подходит вместо `emplace`? 
2. можно делать `layer->result->output`, с optional можно обращаться как с указателем

2023-11-01 22:14 UTC, Artem-Goldenberg commented on server/core/Tensor.h
> +    Tensor(const Operation& operation, const std::vector<TensorRef>& parents, bool noGrad = false);
когда собираемся делать бэквард мы сначала выставляем градиент единицу тензору последнего слоя так? Дак вот теперь выставляй просто градиент единицу тензору Output слоя

2023-11-02 06:07 UTC, lpetrov02 commented on server/core/Tensor.h
> +    Tensor(const Operation& operation, const std::vector<TensorRef>& parents, bool noGrad = false);
А чем это лучше?  
Так нам нужно искусственно каждый раз выставлять градиент, а с флагом узел просто не участвует в обучении

2023-11-02 06:09 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +        layer->result.value().output.emplace(Blob{values.size() / width, width, values.data()});
Ок, опять, а в чём пробема `emplace`?  
Ну да, я так сделал, потому что не понял, что можно обращаться как с указателем, но почему *так* - плохо?

2023-11-02 07:11 UTC, Maxon081102 commented on server/core/Operation.cpp
> +
output нужен только для фронта, на cpp есть просто последний слой и все

2023-11-02 07:14 UTC, Maxon081102 commented on server/core/Tensor.h
> +    Tensor(const Operation& operation, const std::vector<TensorRef>& parents, bool noGrad = false);
убираем output и это тоже уходит

2023-11-02 07:19 UTC, Maxon081102 commented on server/api/GraphBuilder.cpp
> +        layer->result.value().output.emplace(Blob{values.size() / width, width, values.data()});
1) Так проще читается + emplace больше в коде нигде не используется и выглядит, как фича ради фичи
2) меньше кода + проще читается + в остальном коде используется ->

2023-11-02 08:29 UTC, lpetrov02 commented on server/core/Operation.cpp
> +
сдаюс

2023-11-02 08:29 UTC, lpetrov02 commented on server/core/Operation.cpp
> +
сдаюс

2023-11-02 08:29 UTC, lpetrov02 commented on server/core/Tensor.h
> +    Tensor(const Operation& operation, const std::vector<TensorRef>& parents, bool noGrad = false);
железно

2023-11-02 08:37 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +        layer->result.value().output.emplace(Blob{values.size() / width, width, values.data()});
1. Всё-таки не я эту фичу писал, она ж из коробки  
2. Без неё почему-то не работает, видимо, разница есть всё-таки  
Так что давайте пока так оставим

2023-11-02 08:37 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +        layer->result.value().output.emplace(Blob{values.size() / width, width, values.data()});
А, я понял, `->` могу добавить, это ок

2023-11-02 11:19 UTC, Artem-Goldenberg commented on server/api/GraphBuilder.cpp
> +        layer->result.value().output.emplace(Blob{values.size() / width, width, values.data()});
а ну ок тогда, да emplace действительно здесь нужен, потому что у `Blob` делается move, он специально для этого и нужен

2023-11-02 11:19 UTC, Artem-Goldenberg commented
Влей апдейты сюда еще

2023-11-02 11:21 UTC, lpetrov02 commented
Я не вилваю апдейты, потому что Максим от меня ответвился и уже ребейзнулся  
Хочу, чтобы он влил - и тогда добавлю, чтобы не усложнять ему жизнь

2023-11-02 11:22 UTC, Artem-Goldenberg commented
аа ну ок да

2023-11-02 11:53 UTC, lpetrov02 commented
Апдейты доехали

2023-11-02 20:54 UTC, Artem-Goldenberg approved these changes

2023-11-06 11:44 UTC, Maxon081102 commented on server/core/Layer.cpp
> +        b.emplace(dataInit(1, params.outFeatures, randomInit));
- [ ] emplace убрать

2023-11-06 11:44 UTC, Maxon081102 commented on server/core/Tensor.cpp
> +            output.emplace(Blob{dims[0], dims[1]});
emplace

2023-11-06 11:46 UTC, Maxon081102 approved these changes

2023-11-06 13:14 UTC, Artem-Goldenberg commented on server/core/Tensor.cpp
> +            output.emplace(Blob{dims[0], dims[1]});
emplace нужен мы ж решили

2023-11-06 15:32 UTC, merged