ID-96: implement virtual mode for allocator
SPbuMinecraft/GraphicalEditorForNN pull request #35
Opened 2023-10-28 13:37 UTC by Maxon081102

https://ru.yougile.com/team/b400e1850fe9/#chat:d451d1f635ee

2023-10-29 10:46 UTC, Artem-Goldenberg requested changes
Ага, хорошо, чуть подправить
Вообще принцип работы с аллокатором красивый получился 
Да и вообще принцип работы с нейронной сетью крутой, надо только подумать как сделать несколько локаторов, и как избавиться от этого `kostyl` ну я посмотрю это

2023-10-29 10:46 UTC, Artem-Goldenberg commented on server/core/Blob.h
> +    static Blob constMemoryBlobRandom(std::size_t rows, std::size_t cols, RandomObject* object = nullptr);
Мне кажется можно просто `constBlob` и `constRandomBlob`
Еще зачем нам и такие методы и конструктор с флагом, давай конструктор с флагом как раз private будет и будем использовать только эти методы

2023-10-29 10:46 UTC, Artem-Goldenberg commented on server/core/Allocator.h
> +    SessionBuffer& buf = virtBuf;
мы же хотели эти штуки сделать отдельной структурой

2023-10-29 10:46 UTC, Artem-Goldenberg commented on server/core/Allocator.h
> +    static void endVirtMode();
Ну тут все таки интерфейс публичный, давай назовем официально: `startVirtualMode`

2023-10-29 10:46 UTC, Artem-Goldenberg commented on server/core/Allocator.cpp
> +}
Да блин, еще раз: когда ты в `dict` берешь значение по ключу которого нет, он автоматически инитит значение по этому ключу дефолтным инициализатором, то есть `size_t()`, то есть `0`, как раз то что нам нужно

2023-10-29 10:46 UTC, Artem-Goldenberg commented on server/core/Allocator.cpp
> +            memcpy(tmp, buf.base, buf.size - size);
buf.size - size = buf.top

2023-10-29 10:46 UTC, Artem-Goldenberg commented on server/core/Allocator.cpp
> +    }
А кстати ты не удаляешь потом все constMems в `end`

2023-10-29 10:46 UTC, Artem-Goldenberg commented on server/core/Allocator.cpp
> +        Stack &s = instance->pointerTable[shape];
опять же тут когда ты обратишся к `pointerTable[shape]`, создастся `Stack` у которого будет `top = 0` (Если не будет, то добавь конструктор `Stack()`)

2023-10-29 10:46 UTC, Artem-Goldenberg commented on server/core/Allocator.cpp
> +    }
1. Даа, маловато пробелов что-то в 32 строчке
2. ну назови ты key -> pointer, value -> stack, а то нифига не понятно
3. у тебя в `pointers` лежат все указатели, которые на куче, их же надо освободить

2023-10-29 10:46 UTC, Artem-Goldenberg commented on server/core/Allocator.cpp
> +    }
А зачем здесь size снова ставить на 256?
И если не надо, то получается и maxBufferSize не нужен

2023-10-29 10:46 UTC, Artem-Goldenberg commented on server/core/Allocator.cpp
Тебе CI говорит включить сюда cstring

2023-10-29 10:46 UTC, Artem-Goldenberg commented on server/core/Allocator.cpp
> +    instance->sessionPointers = instance->realSessionPointers;
`sessionsPointers` не зависит от реального и виртуального, их можно не менять

2023-10-30 19:13 UTC, Artem-Goldenberg commented
И еще влей апдейт у тебя там конфликты) (Ну да ну да я ребейзнул и что и что)

2023-11-01 17:14 UTC, MaxVorosh approved these changes
Вроде ок, но подожди ещё ревью Артёма

2023-11-02 02:27 UTC, Artem-Goldenberg requested changes

2023-11-02 02:27 UTC, Artem-Goldenberg commented on server/core/Allocator.cpp
> +    }
Так если фиксированный буфер то это уже надо убрать, я тебе так просто не дам замерджить ахахаха

2023-11-02 02:28 UTC, Artem-Goldenberg commented on server/core/Allocator.cpp
> +    Stack &s = instance->info.pointerTable[shape];
кстати теперь если у нас есть info можем вначале писать просто `auto &info = instance->info` и не писать instance каждый раз

2023-11-02 07:21 UTC, Maxon081102 commented on server/core/Allocator.cpp
> +    }
да, я забыл про это, исправлю

2023-11-02 11:47 UTC, Artem-Goldenberg approved these changes
Все четко

2023-11-02 12:24 UTC, merged