Task83 login screen
SPbuMinecraft/GraphicalEditorForNN pull request #38
Opened 2023-11-02 17:36 UTC by heartmarshall

2023-11-02 19:35 UTC, MaxVorosh approved these changes
Выглядит правдоподобно

2023-11-03 19:43 UTC, Artem-Goldenberg requested changes

2023-11-03 19:43 UTC, Artem-Goldenberg commented on client/scripts/auth.js
> +const py_server_port = "localhost:3000"
А ты не можешь достать этот порт из `config.json` файла?

2023-11-03 19:43 UTC, Artem-Goldenberg commented on client/scripts/icons.js
а у там вот я тоже вижу иконки и они лежат в папке `client/static/incons` можешь свои тоже туда добавить?

2023-11-03 19:43 UTC, Artem-Goldenberg commented on client/styles/auth.css
> +    overflow: hidden; /* Убираем прокрутку страницы, если контент слишком большой */
Нифига, даже коменты, вот это круто!

2023-11-03 19:43 UTC, Artem-Goldenberg commented on client/templates/hellopage.html
Ну ладно пускай тестовая страница будет, но что не понял зачем эта страница? Она у меня пустая просто

2023-11-03 19:43 UTC, Artem-Goldenberg commented on client/templates/authorization.html
> +}
эээм нет, я конечно не фронтендер, но разве это не должно быть тоже в js файле?

2023-11-03 19:43 UTC, Artem-Goldenberg commented on client/scripts/auth.js
> +}
Блин ну камон, ну ты же в любом случае просто бросаешь нас на mlcraft неважно авторизованы мы или нет. Ну ладно, это уже исправлено в релизе

2023-11-03 19:43 UTC, Artem-Goldenberg commented on py_server/mlcraft/db.py
> +from sqlite3 import IntegrityError
какой еще sqlite3 ? Давай без него

2023-11-03 19:43 UTC, Artem-Goldenberg commented on py_server/mlcraft/db.py
> +from . import errors
можно вроде просто `import .errors`

2023-11-03 19:43 UTC, Artem-Goldenberg commented on py_server/mlcraft/db.py
> +            # Не очень хорошее решение по обработке ошибок... А если ошибок станет 10, 100?
Да это правда, поэтому мы вообще планировали в отдельном тикеты это решить тем, что у нас будет просто свой класс `DBError` например, наследуется от `Error` и несет в себе message какйо-то и просто его везде кидать. Но это уже в другом тикете так что пока можно так оставить

2023-11-03 19:43 UTC, Artem-Goldenberg commented on py_server/mlcraft/server.py
> +            jsonify({"error": str(e), "problemPart": "username"}),
`jsonify` не нужнен, просто его можно убрать

2023-11-03 19:43 UTC, Artem-Goldenberg commented on client/templates/hellopage.html
вот это вметсе с testpage.html не нужно, надо удалить

2023-11-03 19:43 UTC, Artem-Goldenberg commented on py_server/mlcraft/db.py
> +            existing_user = User.query.filter_by(login=user_parameters["login"]).first()
да, это мы уже договорились потом сделать класс `Error(string)`   и его кидать как исключение, но это уже потом сделаем

2023-11-06 15:55 UTC, heartmarshall commented on client/scripts/auth.js
> +const py_server_port = "localhost:3000"
Я не знаю как(

2023-11-06 15:55 UTC, heartmarshall commented on client/scripts/icons.js
Эти иконки тоже я добавил. Разделение пусть остаётся - в статике хранятся сами файлы иконок, а в js скрипты для работы с ними

2023-11-06 15:56 UTC, heartmarshall commented on py_server/mlcraft/db.py
> +from . import errors
Да, исправил

2023-11-06 16:01 UTC, heartmarshall commented on client/templates/hellopage.html
готово

2023-11-06 16:01 UTC, heartmarshall commented on py_server/mlcraft/server.py
> +            jsonify({"error": str(e), "problemPart": "username"}),
убрал

2023-11-06 16:09 UTC, Artem-Goldenberg commented on client/scripts/icons.js
ааа ну ладно

2023-11-06 16:54 UTC, Artem-Goldenberg approved these changes

2023-11-06 16:55 UTC, merged