ID-129: Implement inputs order in python
SPbuMinecraft/GraphicalEditorForNN pull request #41
Opened 2023-11-07 19:19 UTC by MaxVorosh

[ID-129](https://ru.yougile.com/team/b400e1850fe9/#chat:7bb00fbc7608)

2023-11-08 03:24 UTC, Artem-Goldenberg requested changes
Так ну там чуть подправить, ну так если работает то отлично. 
Надо еще как-то синхронизировать запросы фронтенда теперь с этим и плюс Лене сказать что теперь так, а то он там сейчас пишет форматы для старых запросов 
Офигеть, я так посчитал, я считай 120 строчек смотрел полчаса наверное, ну тут конечно везде содержательный код, но все равно да, я конечно теперь понимаю каково смотреть огромные пр...

2023-11-08 03:24 UTC, Artem-Goldenberg commented on py_server/mlcraft/db.py
> +                "connections": [],
может быть назвать тогда parents чтобы было понятно какие соединения

2023-11-08 03:24 UTC, Artem-Goldenberg commented on py_server/mlcraft/db.py
>              model_items["layers"] = new_layers_list
Так стоп, я знаю что это не в этом пре, но я как то это пропустил, зачем здесь новый список слоев создается, почему просто не удалить слой из model_items?

2023-11-08 03:24 UTC, Artem-Goldenberg commented on py_server/mlcraft/db.py
> +                filter(lambda layer_id: layer_id != layer_from, layer["connections"])
не, если слоя не найдется тебе итератор вернет не None, а бросит StopIteration. Чтобы он None вернул надо там дефолтные параметр где-то прописать, не помню точно лучше загуглить
+
лучше проверять на None не `if not layer` а `if layer is None` потому, что на первое проходит и 0 и False и тд, а на второе только None
+ 
Опять, можно же сделать `del layer["connections"][layer_from]` (удалить ключ из словаря) , и не создавать `new_connections` (при этом тут можно и проверить, валидное ли мы вообще соединение хотим удалить)

2023-11-08 03:24 UTC, Artem-Goldenberg commented on py_server/mlcraft/server.py
> +            int(json["layer_from"]), int(json["layer_to"]), model_id
ага, то есть на фронтенде теперь надо поменять это тоже будет, ну надо создать задачу очередную

2023-11-08 03:24 UTC, Artem-Goldenberg commented on py_server/mlcraft/server.py
> +def shuffle_inputs(user_id: int, model_id: int):
аа это типа когда мы захотели изменить порядок входов? Ну может тогда назовем `update_parents_order` или что-то такое, а то у меня `shuffle` ассоциируется с рандомно перемешать, я все думал, зачем пользователю их перемешивать...

2023-11-08 03:24 UTC, Artem-Goldenberg commented on py_server/mlcraft/utils.py
>      return edges
```python
edges = defaultdict(list)
for layer_to in model_dict["layers"]:
  for layer_from in layer_to["connections"]:
    edges[layer_from].append(layer_to["id"])
```
или еще можешь попробовать в одну строчку с dict comprehension, но у меня не получается

2023-11-08 03:24 UTC, Artem-Goldenberg commented on py_server/mlcraft/db.py
> +            model = Model.query.get(model_id)
короче это оказался неправильный метод, он deprecated. Нужно использовать `db.session.get(Model, model_id)`

2023-11-08 03:24 UTC, Artem-Goldenberg commented on py_server/mlcraft/db.py
> +            if set(layer["connections"]) != set(new_connections) or len(
окей с set я понял, а зачем еще отдельно len проверять, ну наверное даже если чувак заслал два одинаковых id то это ничего страшного?

2023-11-08 03:28 UTC, Artem-Goldenberg commented on py_server/mlcraft/db.py
> +            layer = next(l for l in model_items["layers"] if l["id"] == layer_to)
еще учитывай тут тоже, что слоя с таким id может не быть, я там выше писал по подробнее про это

2023-11-08 17:27 UTC, MaxVorosh commented on py_server/mlcraft/server.py
> +            int(json["layer_from"]), int(json["layer_to"]), model_id
Это делает Ваня, я ему говорил

2023-11-08 17:30 UTC, MaxVorosh commented on py_server/mlcraft/db.py
> +            if set(layer["connections"]) != set(new_connections) or len(
Но тогда какое из них валидное? И в целом, кажется, что это неправильный запрос, а значит нужно выдать ошибку

2023-11-08 17:31 UTC, MaxVorosh commented on py_server/mlcraft/db.py
> +            layer = next(l for l in model_items["layers"] if l["id"] == layer_to)
Это метод добавления, когда мы уверены, что можем добавить. Проверки делаются до вызова этого метода

2023-11-08 18:12 UTC, Artem-Goldenberg commented on py_server/mlcraft/db.py
> +            layer = next(l for l in model_items["layers"] if l["id"] == layer_to)
аа окей

2023-11-08 18:24 UTC, Artem-Goldenberg commented on py_server/mlcraft/db.py
> +            if set(layer["connections"]) != set(new_connections) or len(
ну ладно, ну ты можешь тогда сделать `sorted(connections) == sorted(new_connections)`

2023-11-09 15:49 UTC, AntoxaBarin approved these changes

2023-11-09 18:09 UTC, Artem-Goldenberg approved these changes
Отлично! Все круто, там подправь только название и можно вливать

2023-11-09 18:09 UTC, Artem-Goldenberg commented on py_server/mlcraft/server.py
> +def shuffle_inputs(user_id: int, model_id: int):
здесь подправь только на update_parents_order

2023-11-09 18:43 UTC, merged