ID-124: swagger
SPbuMinecraft/GraphicalEditorForNN pull request #43
Opened 2023-11-08 20:39 UTC by lpetrov02

ПР в честь Максима Никитина!!  
Тут отсительно черновой вариант пока что  
Мне не нравится, что в примерах `response` постоянно дублируется одно и то же, вероятно, эти примеры не нужны

2023-11-09 09:48 UTC, Artem-Goldenberg reviewed
хорошо, все правильно делаешь) 
Ну надо конечно чтобы все посмотрели и надо обсудить по поводу переименования ручек, что я там ниже написал

2023-11-09 09:48 UTC, Artem-Goldenberg commented on py_server/mlcraft/server.py
> +        return {"error": response.text}, response.status_code
короче ты здесь можешь возвращать просто `"", HTTPStatus.OK` или попробуй даже `None, HTTPStatus.OK`
ну тогда просто `Response` не нужен

2023-11-09 09:48 UTC, Artem-Goldenberg commented on py_server/mlcraft/server.py
> +            return Response(status=HTTPStatus.OK)
здесь тоже

2023-11-09 09:48 UTC, Artem-Goldenberg commented on py_server/mlcraft/static/swagger.yaml
> +
о вау, крутое описание!

2023-11-09 09:48 UTC, Artem-Goldenberg commented on py_server/mlcraft/static/swagger.yaml
> +      description: "Logins a USER"
ааахха, да я это по приколу написал, можно написать типо, starts a user session я хз

2023-11-09 09:48 UTC, Artem-Goldenberg commented on py_server/mlcraft/static/swagger.yaml
> +  /add_layer{user_id}/{model_id}:
слэш забыл

2023-11-09 09:48 UTC, Artem-Goldenberg commented on py_server/mlcraft/static/swagger.yaml
> +    post:
я вот что подумал, вообще обычно не делают названий типа `add_model` там делают просто `model` и к ней если POST запрос, то это значит добавить, PUT обновить, GET просто получить (как раз load_model) 
то есть может нам переименовать и сделать просто `POST user` вместо `add_user` и так далее?

2023-11-09 09:48 UTC, Artem-Goldenberg commented on py_server/mlcraft/static/swagger.yaml
> +      description: "Adds a new CONNECTION between layers"
ахаха, да не обязательно здесь капсом писать

2023-11-09 09:48 UTC, Artem-Goldenberg commented on py_server/mlcraft/static/swagger.yaml
> +                    example: 1
кстати здесь надо уточнить, там по моему у слоев id начинаются с 0, а у всего остального с 1. Надо об этом тоже написать

2023-11-09 09:52 UTC, Artem-Goldenberg commented
по поводу response дублируется, ну можно их в одну схему в конец вынести

2023-11-09 09:53 UTC, Artem-Goldenberg commented on py_server/mlcraft/static/swagger.yaml
> +  /login_user:
тут еще надо прописать что может вернуть 401 unauthorized

2023-11-09 11:10 UTC, Artem-Goldenberg commented
Кстати еще надо добавить запросы на change parameter order наверное, ну это надо с Максом скооперироваться

2023-11-09 15:40 UTC, lpetrov02 commented on py_server/mlcraft/server.py
> +        return {"error": response.text}, response.status_code
А ой, я кстати думал, что это одно и то же)

2023-11-09 15:41 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +  /add_layer{user_id}/{model_id}:
Поправил, спасибо)

2023-11-09 15:42 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +      description: "Logins a USER"
Прямо так и написал пока

2023-11-09 15:44 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +      description: "Adds a new CONNECTION between layers"
Ну ты начал, я поддержал стиль))

2023-11-09 15:54 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +    post:
Прописал в комментариях `server.py` варианты, потом можем посмотреть, обсудить

2023-11-09 15:54 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +                    example: 1
А какая причина этого явления? Может, логичнее его устранить?

2023-11-09 15:58 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +  /login_user:
Да, пропустил  
Теперь есть

2023-11-09 16:04 UTC, lpetrov02 commented on py_server/mlcraft/server.py
> +        return {"error": response.text}, response.status_code
Ща реально - не одно и то же? Или ты про стиль?

2023-11-09 18:10 UTC, Artem-Goldenberg commented on py_server/mlcraft/server.py
> +        return {"error": response.text}, response.status_code
Да это просто чтобы Response не импортировать

2023-11-09 18:12 UTC, Artem-Goldenberg commented on py_server/mlcraft/static/swagger.yaml
> +                    example: 1
ну надо тоже обсудить

2023-11-09 19:18 UTC, lpetrov02 commented on py_server/mlcraft/server.py
> +        return {"error": response.text}, response.status_code
Поправил

2023-11-09 19:18 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +    post:
Поменял, как на созвоне обсудили

2023-11-09 19:18 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +                    example: 1
Забыли обсудить, пока оставляю как есть

2023-11-09 19:19 UTC, MaxVorosh requested changes
Я, возможно, что-то проглядел. Но как я понял, есть проблемы с тем, как ты указал различные json. Если считаешь, что где-то я указал неправильный формат или не увидел, где лежит тот или иной json - пиши

2023-11-09 19:19 UTC, MaxVorosh commented on py_server/mlcraft/static/swagger.yaml
> +  /add_model/{user_id}:
А как мы здесь учитываем, что мы передаём json с полем name?

2023-11-09 19:19 UTC, MaxVorosh commented on py_server/mlcraft/static/swagger.yaml
> +          }
По-моему, сейчас parameters это просто строка, разделённая символом (;)

2023-11-09 19:19 UTC, MaxVorosh commented on py_server/mlcraft/static/swagger.yaml
> +          }
Та же проблема с parameters

2023-11-09 19:19 UTC, MaxVorosh commented on py_server/mlcraft/static/swagger.yaml
> +          example: "Linear"
В update_layer нам нужен не тип, а id

2023-11-09 19:19 UTC, MaxVorosh commented on py_server/mlcraft/static/swagger.yaml
> +              $ref: '#/components/schemas/Connection'
Нам же в clear_model вообще не нужен json

2023-11-09 19:19 UTC, MaxVorosh commented on py_server/mlcraft/static/swagger.yaml
> +  /add_connection/{user_id}/{model_id}:
А в add_connection нужен json

2023-11-09 19:19 UTC, MaxVorosh commented on py_server/mlcraft/static/swagger.yaml
> +                  example: 1
1. Мне пришлось поменять в своём pr формат этого json. Теперь там 2 поля с int - layer_from и layer_to

2. Я добавил новую ручку - /update_parents_order/int:user_id/int:model_id. В неё передаётся json с двумя полями - layer_id (int) и new_parents (list(int))

2023-11-09 19:19 UTC, MaxVorosh commented on py_server/mlcraft/static/swagger.yaml
> +  /train/{user_id}/{model_id}/{safe}:
Мы сюда передаём json с единственным полем dataset. Какой он должен быть по формату я точно не знаю, т.к. нигде его не использовал

2023-11-09 19:19 UTC, MaxVorosh commented on py_server/mlcraft/static/swagger.yaml
> +  /predict/{user_id}/{model_id}:
Сюда тоже передаётся json. В нём 2 поля - x и y. Потом, скорее всего, они поменяются, но пока так

2023-11-09 19:22 UTC, MaxVorosh commented on py_server/mlcraft/static/swagger.yaml
> +                    example: 1
Да, это можно устранить, но аккуратно. Как минимум в одном месте (когда конструирую json для отправки на сервер C++ в predict) я пользуюсь тем, что 0-й слой - это Data
Изначально такая проблема возникла, т.к. у большинства объектов id задаётся СУБД, где нумерация с единицы. А слои мы храним просто списком json в одном поле БД. И там я по привычке нумеровал с нуля

2023-11-09 19:25 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +  /add_model/{user_id}:
У нас в `add_layer` обязательно нужно `name`?

2023-11-09 19:27 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +          }
Оу, ладно))  
Поправил

2023-11-09 19:28 UTC, MaxVorosh commented on py_server/mlcraft/static/swagger.yaml
> +  /add_model/{user_id}:
Да. Там есть такая строчка:
inserted_id = sql_worker.add_model(user_id, json["name"])
И концептуально, пользователь умеет давать имя модели. Значит мы должны его хранить и запрашивать. А это только через посылку json можно

2023-11-09 19:32 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +              $ref: '#/components/schemas/Connection'
О, это копипаста приехала, сорян

2023-11-09 19:33 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +  /add_connection/{user_id}/{model_id}:
Я понял, почему-то это json оказался в `clear_model`. Вроде сейчас расставил по местам

2023-11-09 19:34 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +  /train/{user_id}/{model_id}/{safe}:
А это правда? По-моему, было бы логичнее данные добавить как любой другой слой, а тут уже просто запустить обучение

2023-11-09 19:34 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +  /predict/{user_id}/{model_id}:
Тот же вопрос: не лучше ли загружать данные заранее, раз уж они сделаны как слой?

2023-11-09 19:42 UTC, MaxVorosh commented on py_server/mlcraft/static/swagger.yaml
> +  /train/{user_id}/{model_id}/{safe}:
Пока что они передаются через json. Я не настолько опытен, чтобы точно сказать, как лучше. Можешь обсудить с Артёмом этот момент. Но пока что dataset передаётся в json, поскольку он снимается с формочки на сайте

2023-11-09 19:43 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +  /train/{user_id}/{model_id}/{safe}:
Я понял, давай до завтра оставим

2023-11-09 19:44 UTC, MaxVorosh commented on py_server/mlcraft/static/swagger.yaml
> +  /predict/{user_id}/{model_id}:
Тот же ответ)
Пока что это передаётся в json. Возможно, это не оптимально. Тогда можешь переделать

2023-11-09 19:44 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +                  example: 1
После ребейза подстроюсь

2023-11-09 19:45 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +  /predict/{user_id}/{model_id}:
Короче завтра обсудим, если что - переделаю (только фронт тоже придётся напрячь)

2023-11-09 20:06 UTC, Artem-Goldenberg commented on py_server/mlcraft/static/swagger.yaml
> +                    example: 1
Ну ладно давайте пока оставим, отдельным пром уберем если что, пока просто надо про это написать

2023-11-09 20:15 UTC, Artem-Goldenberg commented on py_server/mlcraft/static/swagger.yaml
> +          }
а ты запрос с такими параметрами пробовал делать? проходит?

2023-11-09 20:15 UTC, Artem-Goldenberg commented on py_server/mlcraft/static/swagger.yaml
> +          }
просто по моему там надо равно ставить а не двоеточие

2023-11-09 20:17 UTC, MaxVorosh commented on py_server/mlcraft/static/swagger.yaml
> +          }
Я писал про точку с запятой. Да, имел в виду "parameter1=value1;parameter2=value2..."

2023-11-09 20:19 UTC, Artem-Goldenberg commented on py_server/mlcraft/static/swagger.yaml
> +  /train/{user_id}/{model_id}/{safe}:
Ну хз мне кажется датасет хранить в бд это так себе, тем более сейчас в пре он у меня уже вообще через csv файл передается

2023-11-09 20:20 UTC, Artem-Goldenberg commented
У тебя там тесты валятся, потому что ты методы поменял, тесты тоже надо

2023-11-09 20:21 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +  /train/{user_id}/{model_id}/{safe}:
хм ладно ладно, давай переделаю

2023-11-09 20:21 UTC, Artem-Goldenberg commented on py_server/mlcraft/static/swagger.yaml
> +  /predict/{user_id}/{model_id}:
Ну предикт это тоже csv будет, его пихать разве что в Data, но по моему логичнее уже передавать при нажатии на кнопку predict

2023-11-09 20:23 UTC, Artem-Goldenberg commented
Макс, красава классно отревьюил, много ошибок нашли 
Надо еще Ваню добавить сюда, он же фронт делает

2023-11-09 20:55 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +  /train/{user_id}/{model_id}/{safe}:
Переписал с датой. Только я сделал два поля - всё-таки нам для трейна нужно два набора данных..

2023-11-09 20:57 UTC, MaxVorosh commented on py_server/mlcraft/static/swagger.yaml
> +  /train/{user_id}/{model_id}/{safe}:
По-моему, они упаковываются в 1 массив

2023-11-09 20:57 UTC, lpetrov02 commented on py_server/mlcraft/static/swagger.yaml
> +  /predict/{user_id}/{model_id}:
Сделал два поля, пусть пока будет так

2023-11-09 20:58 UTC, lpetrov02 commented
> Макс, красава классно отревьюил, много ошибок нашли Надо еще Ваню добавить сюда, он же фронт делает

Да, реально!! Спасибо тебе большое и извини за глупые ошибки..

2023-11-09 21:26 UTC, lpetrov02 commented
Там в тестах что-то не так с `py.typed` или чем-то ещё  
Пока не понял, как чинить. Артём, если ты знаешь, то завтра (сегодня) подскажи плиз, если нет, то забей, я сам погуглю утром

2023-11-10 12:13 UTC, AntoxaBarin approved these changes
Мне все нравится, все равно на фронтенде надо подстраиваться под новые ручки, так что под небольшие изменения в json'ах тоже подстроимся. Вообще, swagger - крутая штука.

2023-11-10 18:28 UTC, MaxVorosh approved these changes

2023-11-12 01:00 UTC, lpetrov02 commented
Я потестил сваггер, + ещё немного поменял ручки для соответствия сваггеру там, где это было, на ой взгляд, логично.  
Есть проблема с `connections`, там нужны поля `inputs` и `outputs`, а их нет. Причём это берётся из базы, так что бага относится не к этой задаче  
В остальном - более-менее, считаю, что можно вливать и потом атомарно править при необходимоти (в том числе ту штуку с датасетом)

2023-11-15 22:20 UTC, AntoxaBarin commented
Так я оживил `add_connection` и `delete_connection`. 
Есть один нюанс: питоновский сервер возвращает в качестве положительного ответа в некоторых запросах пустую строку `""`. Из-за этого в консоли в браузере выводится не `Fetch finished loading`, а `Fetch failed loading`, но это **не влияет** на работу запросов к бд, всё работает, просто это такой баг `fetch`'а.

2023-11-15 22:22 UTC, AntoxaBarin commented on client/templates/main.html
> +            Connections: data2.Connections.concat(`${data1.DBID};${connection.output_id}`), // "db_id;drawflow_id"
Теперь храним в соединениях еще и локальный (из библиотеки drawflow) id слоев. Это нужно для выбора входов, пока здесь нет выбора входов, но оно не мешает.

2023-11-15 22:25 UTC, AntoxaBarin commented on client/templates/main.html
> +        pos_x -= 100
Эти две строки ставят слой на канву относительно центра блока, а не относительно левого верхнего края. Это не решает таску о корректном размещении блока на канве [(id-110)](https://ru.yougile.com/team/b400e1850fe9/#GRA-110), но это лучше, чем ничего.

2023-11-15 22:29 UTC, AntoxaBarin commented on py_server/mlcraft/server.py
> +        return "", HTTPStatus.OK
Вот та самая пустая строка, из-за которой ругается `fetch` (на работу запросов не влияет)

2023-11-17 00:11 UTC, merged