ID-116: implement blob with 4 dims
SPbuMinecraft/GraphicalEditorForNN pull request #46
Opened 2023-11-12 10:40 UTC by Maxon081102

https://ru.yougile.com/team/b400e1850fe9/#ID-116

2023-11-12 15:09 UTC, Artem-Goldenberg reviewed
Уфф даа это было долго, ну это работа в процессе же да? Ну вообщем вот написал что думаю

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/Allocator.cpp
>      for (auto const [shape, count]: counts) {
Так ну во первых здесь надо ссылку, там даже компилятор подсказывает

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/Allocator.cpp
> +    hash_combine(seed, hash<size_t>()(shape.size()));
эээм не не не, у нас тогда shape(2, 3) будет иметь тот же хэш что и shape(3, 2)

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/Shape.h
> +    Shape(std::size_t dim4, std::size_t dim3, std::size_t rows, std::size_t cols, short int dimsCount);
просто short

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/Shape.h
> +};
Добавляйте новую строчку в конец файла всегда, а то у некоторых, в том числе и у меня IDE само всегда пытается добавить постоянно diff какой-то получается

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/Shape.cpp
> +    dim4(dim4), dim3(dim3), rows(rows), cols(cols), dimsCount(dimsCount) { fillDims(); }
Ну тут их надо в обратном порядке определять, тогда сможешь их переиспользовать, например Shape(cols): Shape(1, cols) и тд

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/Shape.cpp
> +    return this->cols == other.cols && this->rows == other.rows && this->dim3 == other.dim3 && this->dim4 == other.dim4;
нет ну здесь то this не нужен

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/LazyBlob.h
> +    float operator() (std::size_t j) const { return (*this)(0, 0, 0, j); };
о ну да прикольно да, нормально, но только зачем нам теперь rows и cols если уже shape есть, ну или добавь тогда уже и dim3 и dim4

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/Shape.h
> +    std::size_t dimsMult[4];
аа ну я наконец понял что это значит, в numpy это называется `stride`

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/Blob.cpp
> +    }
ахаха не ну хорошо что ты скобочки не стал расставлять на каждом цикле это хорошо. 
Но тут же можно только последним циклом обойтись, и еще это работает только для 2 мерных блоков ты же там не тот конструктор вызываешь, и еще, на кой там this? 
И еще, замечание в виде загадки, разгадаешь? У нас были только верблюды, а ты притащил змею, зачем?

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/Blob.cpp
> +    size_t indexes[] = {k, l, i, j};
indices

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/Blob.cpp
> +    // assert(shape.dimsCount != 0);
а чего, оставь assert, чем больше тем лучше

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/Blob.h
> +    static Blob constBlobRandom(Shape shape, RandomObject* object = nullptr);
constRandomBlob

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/Iterations.h
> +void opp(
Ну назови поприличнее, хотя бы map

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/Iterations.h
> +    std::vector<std::size_t> indexes = {}
indices

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/Iterations.cpp
> +}
Ну функция крутая, да
Там точно нам надо и `axis` и `sizes`, если мы не хотим итерироваться по определенной оси то просто передать 1 на это место в массиве sizes нельзя?
и кстати, если ты знаешь что axis и sizes будут всегда 4, то можно так и передать `size_t sizes[4]`

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +    }
Ну то есть ты еще стретчинг по 3 и 4 не поддерживаешь так?

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +class LazyBlobSelfOperation: public LazyBlob {
ReduceOperation, я же правильно понял что это операции типа пронумеровать по строчкам и тд?

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +    }
уфф уфф, это мощная функция. Просто 
```C++
Shape result = a.shape()
for (auto dim: axis) result[dim] = 1;
return result;
```

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +        size_t size[] = {0, 0, 0, 0};
```C++
bool axis[4] = {};
size_t size[] = {};
```
тоже сработает

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +        }
ну вот реально получается же что axis в opp не нужен просто на месте где нам не надо итерироваться пиши 1 в size, то есть 
```C++
size_t size[] = {1, 1, 1, 1}; // да, тут надо писать везде 1
auto shape = a.shape(); // лучше закэшировать все таки
for (auto dimIdx: axis) size[dimIdx] = shape.dims[dimIdx];
```
Еще я бы все таки хранил в axis те оси которые надо стереть а не оставить

2023-11-12 15:09 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +        });
ну то есть все еще тут не поддерживаются выше двух размерностей как я понимаю

2023-11-13 00:28 UTC, Artem-Goldenberg commented
Еще: можешь переопределись оператор `[]` для Shape

2023-11-13 00:33 UTC, Artem-Goldenberg commented
Всеее я понял как там матрицы моим способом перемножать, смотри вот допустим у нас есть такие размерности:
`(rows, cols, depth, time)`

Перемножение:
`(h, a, d, t) * (a, w, d, t) = (h, w, d, t)`

Транспонирование:
`(h, w, d, t)T = (w, h, d, t)`

То есть это все то же что и у тебя, только размеренности зеркально наоборот записываются
И тогда инит для Shape можно сделать такой:
`Shape(int rows = 1, int cols = 1, int depth = 1, int time/batch = 1)`

Тогда индоссируем так:
`operator [] (int i, int j = 0; int d = 0; int t = 0)`

2023-11-17 00:23 UTC, Artem-Goldenberg commented
Вот смотри все просто:
что такое например  $v \in N^3$ - это 
```math
v = 
\begin{bmatrix}
           a_{1} \\
           a_{2} \\
           a_{3}
 \end{bmatrix}
```

А что такое $M \in N^{3x2}$ - это 
```math
M = 
\begin{bmatrix}
           a_{11} & a_{12} \\
           a_{21} & a_{22} \\
           a_{31} & a_{32}
\end{bmatrix}
```

То есть у нас был вектор с 3 строками, и мы каждую строчку растянули на 2, вот так получилась матрица. 
Соответственно $\mathcal{M} \in N^{3x2x4}$ - это у нас была матрица 3x2 и мы каждую клетку там растянули на 4, так получился куб

2023-11-24 09:56 UTC, Maxon081102 commented on server/core/LazyBlob.cpp
> +class LazyBlobSelfOperation: public LazyBlob {
это откуда ?

2023-11-24 17:33 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +class LazyBlobSelfOperation: public LazyBlob {
смысле откуда? там же написано 56 строчка

2023-11-27 10:16 UTC, Artem-Goldenberg commented
Ага, а у тебя там комит нызвается IDE ахаха, вообще надо сделать хуки на формат комитов

2023-11-27 11:58 UTC, Artem-Goldenberg requested changes
ФУХ, ну наконец-то оно закончилось 
Даа, ну развлекайся там ахахах
Там много каких моментов есть обсудить, все таки зря мы такие огромные Пры делаем 
Ну вот тепеерь понимаешь почему сложно писать хороший код ахаха

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Blob.cpp
> +                    this->operator()(k, l, i, j) = other(k, l, i, j);
это че за фигня???

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Shape.h
> +struct Shape {
Компилятор ругается, что здесь нужно и конструктор копирования определить и оператор = по отдельности

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Stretch.h
> +struct Stretch {
Тоже нужно конструктор копирования и оператор =

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Allocator.h
>  struct std::hash<Shape> {
Так че, давай это тоже в файл Shape.h

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Allocator.cpp
>  size_t hash<Shape>::operator()(const Shape& shape) const {
это все дело тоже

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Blob.h
> +    static Blob constRandomBlob(Shape shape, RandomObject* object = nullptr);
я что то забыл? или можно же эти 2 функции объединить в одну

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Blob.h
> +    static Blob ones(Shape shape = Shape());
а смысл там делать дефолтное значение, а тут нет, лучше дефолт вообще убрать

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Blob.h
> +    Blob(Shape shape, bool constMemory, RandomObject* object = nullptr);
Опять, запихни все в один

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Blob.cpp
> +Blob::Blob(float value): Blob(Shape(), &value) {};
ну вот это не хорошо, не понятно где там какой конструктор вызывается, нужно как я сказал все приватные конструкторы в один запихнуть

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Blob.cpp
> +}
ты здесь специально assert не ставишь?

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Blob.cpp
>  };
нифига, не ну раз 4 мерный блоб делаешь, напиши чтоб он выводился нормально

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Iterations.h
> +    std::vector<std::size_t> indexes = {}
нет ну все же indices

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Iterations.cpp
> +        }
тут поехала скобочка

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +        });
все таки зря я убрал варнинг об неиспользованном параметре, у тебя тут l1 2 раза

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.h
> +
куда линию добавил, убери ахаха

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.h
> +    const LazyBlob& mean(std::vector<short> axis) const;
нет ну если ты хочешь ТАКУЮ оптимизацию что прям аж short, то передавай тогда уже unsigned char, но сделай typedef на нормальное имя сначала

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.h
> +    const LazyBlob& increase(Shape shape) const;
вот к такому хорошо комментарии какие-нибудь написать, я вообще не понимаю че это делает

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.h
> +    std::size_t cols() const { return shape().cols(); };
ну надо убрать rows и cols

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
>  #include "LazyBlob.h"
ну поставь LazyBlob.h первым здесь

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.h
> +    virtual Shape shape() const = 0;
ну все таки тут уже лучше const Shape& потому что там в Shape дофига всего и это будет копироваться по всему дееревуу...., не очень красиво будет

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +class LazyBlobSelfOperation: public LazyBlob {
Окей давай назовем это LazyBlobTransformOperation
И отнаследуем LazyBlobReductOperation

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +                axis[3] ? l1 : indices[3]
ну это специально? это же не специально, правда?

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Iterations.h
> +std::vector<std::size_t> fillSize(std::vector<bool> axisForIter, Shape shape);
ну Макс, ну это жесть, по коду не понятно для чего там эти indexes, и непонятно вообще какой параметр за что отвечает и по какими значениям все таки будет вызываться эта функиця f
Напиши комментарии, формат лучше такой же взять как в Allocator
И по fillAxis и по fillSize тоже напиши

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Iterations.h
> +std::vector<std::size_t> fillSize(std::vector<bool> axisForIter, Shape shape);
И еще лучше вектора все таки по const & прокидывать

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +        });
ну тут у меня много вопросов 
1. зачем indices, ты их тут только как k l i j и используешь
2. ну сделай чтобы fillAxis возвращал bool[4] какой-нибудь
3. не понимаю все эти  axis[0] ? k1 : indices[0], то есть если мы схлопываем по этой оси, то возьми индекс по которому итерируемся, но разве все эти индексы не будут всегда 0?

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +class LazyBlobSelfMean final: public LazyBlobSelfOperation {
Ну Mean можно было бы реализовать как Sum а потом деление просто
но можно и так оставить это просто мысли

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +};
Тут те же вопросы что и в Sum

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +class LazyBlobSelfIncrease final: public LazyBlobSelfOperation {
ну, ох уж эти названия, ну мы ж хотели Fill ну или Stretch тут тоже подходит, и Self убери, ну пожалуйста

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +        for (int i = 0; i < 4; i++) {
ну кстати говоря вот это 4 хорошо бы вынести в какой нибудь #define

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +class LazyBlobSelfIncrease final: public LazyBlobSelfOperation {
еще мысль, что можно reshape операцию обобщить тоже до этого случая

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +            }
ну - за скобки

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +                assert(false);
ну напиши комент из-аз чего этот assert может сработать

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +        });
ну блин почему здесь порядок i j k l это нормально? а раньше был другой

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +
ну уффф, давай ты лучше напишешь тесты на все эти += операции, потому что ну это капец здесь логики, я уже хз правильно это, не правильно...

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
> +
а ну + здесь точно неправильно, потому что тут опять только 2мерный случай

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/LazyBlob.cpp
>  }
ну надо написать для 4х мерного все же это все

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Operation.cpp
> +        stretch = new Stretch(canStretch.second);
ну сделай optional на Stretch, не надо будет деструктор писать

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Operation.cpp
> +        std::pair<bool, Stretch> canStretch = Stretch::canStretch(a.shape(), b.shape());
ну auto [canStretch, theStretch] = ...
как в Allocator

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Shape.cpp
> +Shape::Shape(vector<size_t> dims): Shape(dims, dims.size()) {}
ну (vector<size_t> dims = {})
и проверь можно ли там const vector<size_t>& сделать

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Shape.h
> +    std::size_t stride[4];
ну мы хотели это функцией сделать да

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Shape.h
> +    std::vector<std::size_t> getDims() const;
ну ты нигде это не используешь, правда?

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Shape.cpp
> +    }
ну ладно окей, крутой код, тут понятно что происходит 
не только dims.size() в 17 бесполезный просто 4 сойдет
ну и - за скобки разумеется )

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Stretch.cpp
> +    return std::make_pair(canStretch, Stretch(axisForStretch));
попробуй {canStretch, Stretch(...)};

2023-11-27 11:58 UTC, Artem-Goldenberg commented on server/core/Stretch.cpp
> +    Shape minDimsCount = b;
ладно здесь ок, только непонятно почему maxDimsCount - это Shape 
наверное это можно назвать bigShape smallShape ну или сам придумай

2023-11-27 11:59 UTC, Artem-Goldenberg commented on server/core/Shape.h
> +    std::vector<std::size_t> getDims() const;
я про getDims

2023-12-02 19:43 UTC, Artem-Goldenberg approved these changes
ну вроде норм, но честно мне лень все это еще раз смотреть 
но ПОФИГГ - это наша философия

2023-12-02 19:43 UTC, Artem-Goldenberg commented on server/core/Iterations.h
> +/// - Returns: sizes for iterations from shape and mask
😎

2023-12-03 09:53 UTC, merged