ID-55: style combination
SPbuMinecraft/GraphicalEditorForNN pull request #48
Opened 2023-11-13 19:04 UTC by doejoedoe

[ID-55](https://yougile.com/team/b400e1850fe9/#ID-55)

2023-11-14 08:40 UTC, AntoxaBarin requested changes
![image](https://github.com/SPbuMinecraft/GraphicalEditorForNN/assets/88805084/036cb7d1-c9f5-449c-b39f-e497e71b3612)

Напишу моменты, которые меня смущают. 
1. При наведении на кнопку `Sign up` слегка увеличивается шрифт и кнопка из-за этого увеличивается (просто пошире сделать исходную кнопку, чтоб текст не переносился).
2. Если ввести некорректный пароль, то цвет шрифта меняется на красный. Нужно бы это починить (а, вообще, можно подобрать цвет, который будет выглядит лучше, чем текущий красный, это преподаватель на практике еще подметил).
3. Вкладка профиль: убрать надпись `Coming soon!`. Передвинуть кнопку `sign out` повыше, сделать её побольше.
4. При развернутом меню профиля, если перейти на страницу `Home`, то пользователь увидит пустую белую страницу.

2023-11-14 09:18 UTC, AntoxaBarin commented
Еще небольшой момент. Название страницы авторизации в браузере -- `Visual Networks`. Надо бы поменять на `MLCraft`, чтобы везде было единое название.

2023-11-14 14:50 UTC, Artem-Goldenberg commented
Нам на демо сказали эти красные кнопочки авторизации убрать пока они не работают

2023-11-14 14:50 UTC, Artem-Goldenberg commented
я бы убрал бирюзовую подсветку у MLCraft

2023-11-14 14:52 UTC, Artem-Goldenberg commented
Еще мне кажется либо сразу сделать жирный шрифт для кнопок, либо вообще не делать, потому что когда наводишь на кнопку и там текст становится немного больше это неожиданно

2023-11-15 17:10 UTC, Artem-Goldenberg commented
![photo_2023-11-15 20 09 02](https://github.com/SPbuMinecraft/GraphicalEditorForNN/assets/58527023/68557ac2-5851-4786-a41d-005afd99e449)
Еще так со свежего взгляду я бы увеличил расстояния там где оранжевым отмечено, а то получается у нас все сильно в центре экрана

2023-11-16 18:12 UTC, AntoxaBarin approved these changes

2023-11-16 18:13 UTC, Artem-Goldenberg approved these changes

2023-11-16 18:33 UTC, merged