Fix bug (updating parameters in wrong layer)
SPbuMinecraft/GraphicalEditorForNN pull request #50
Opened 2023-11-21 22:33 UTC by AntoxaBarin

[ID-160](https://ru.yougile.com/team/b400e1850fe9/#GRA-160)
`Баг:` открываем параметры слоя №1, меняем ему какой-нибудь параметр (баг проявлялся с полями ввода, например, inFeatures). Просто записали новое значение параметра, дальше просто кликаем на слой №2 => параметры обновляются у слоя №2, но должны у слоя №1. 

Починил я этот баг достаточно дешево, просто ввел новую переменную. Но это очередная переменная, назначение которой может быть плохо понятно человеку, который полезет разбираться в нашем фронтенде. Поэтому я думаю **завести документацию на фронт** (мб в Notion) - просто будет описана семантика основных методов, описание переменных. 

Сам баг фикс: теперь когда пользователь меняет какие-то данные в параметрах, то программа запоминает id этого слоя. В предыдущей реализации был только `event listener` на событие `change`, то есть прям изменение значения в поле для ввода, ну там надо было Enter нажать, чтоб запрос к бд отработал. А сейчас вообще всегда должно работать, в любом случае правильно запомнится id и отправится запрос к бд.

2023-11-22 17:49 UTC, Artem-Goldenberg requested changes
Круто, только эти вары замени. А так классно даже описание написал, по поводу документации, лучше после этого спринта, когда мы уже все таки ОТДЕЛИМ сам знаешь что. Потому что после этого вся документация может поменяться.

2023-11-22 17:49 UTC, Artem-Goldenberg commented on client/templates/main.html
> +      })
здесь можно не писать слово function, просто () => { ... }

2023-11-22 17:49 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        var parameters = getParametersFromNode(last_changed_parameters_layer_id)
а почему здесь `var` везде? поменяй на let или на const если они не меняются нигде
`var` это будет виден в глобальном скоупе javascript насколько я понимаю

2023-11-22 20:39 UTC, AntoxaBarin commented
Так ну все `var'ы` поменял на `let`, `function () `заменил на `() =>`

2023-11-23 19:22 UTC, Artem-Goldenberg reviewed
Влил тебе мейн, это просто нажмешь на кнопочку update branch если что

2023-11-23 19:22 UTC, Artem-Goldenberg commented on client/templates/main.html
> +      })
Тут забыл

2023-11-23 19:23 UTC, Artem-Goldenberg requested changes

2023-11-23 19:23 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        let new_value = document.getElementById("special-width-parameter").value
а почему let? Константа - это const, а переменная - это let

2023-11-24 14:02 UTC, AntoxaBarin commented
Вроде, всё поменял. Массив `parameters` сделал const, то есть его можно менять, но нельзя присваивать другой массив

2023-11-24 17:34 UTC, Artem-Goldenberg approved these changes

2023-11-24 17:50 UTC, merged