ID-121: Add image loader class
SPbuMinecraft/GraphicalEditorForNN pull request #52
Opened 2023-11-23 18:53 UTC by MaxVorosh

[ID-121](https://ru.yougile.com/team/b400e1850fe9/#GRA-121)

2023-11-23 18:58 UTC, MaxVorosh commented
Я вроде сделал, но не знаю, как это добавить в систему сборки. На самописном Makefile работает

2023-11-24 19:24 UTC, Artem-Goldenberg reviewed
Тесты класс, вообще супер что ты разобрался как работать с этим доктестом даже

2023-11-24 19:24 UTC, Artem-Goldenberg commented on server/api/ImageLoader.h
> +};
если тут не планируется хранить состояние, то можешь сделать функции static, или просто сделать namespace ImageLoader

2023-11-25 20:15 UTC, Artem-Goldenberg commented
Бл это *****, надо было просто в КОНЕЦ команды поставить -lX11 а не в начало, это .......

Ну ладно вообще все линкуется, только в тестах он немного ругается + не ликует api, но это должно исправиться как только зальешь мейн

2023-11-26 18:45 UTC, Maxon081102 requested changes

2023-11-26 18:45 UTC, Maxon081102 commented on server/api/ImageLoader.cpp
> +    std::cout << size << std::endl;
мы точно хотим тут std::cout на каждую фотографию?

2023-11-26 18:46 UTC, MaxVorosh commented on server/api/ImageLoader.cpp
> +    std::cout << size << std::endl;
Упс, проник артефакт

2023-11-26 19:17 UTC, Artem-Goldenberg commented on server/tests/ImageLoaderTests.cpp
> +#include "../api/ImageLoader.h"
можно просто #include "ImageLoader.h там уже хедеры подключаются

2023-11-28 18:15 UTC, Maxon081102 approved these changes

2023-11-28 18:19 UTC, merged