add localStorage restore
SPbuMinecraft/GraphicalEditorForNN pull request #56
Opened 2023-11-24 16:58 UTC by heartmarshall

2023-11-24 17:30 UTC, AntoxaBarin commented
Там, вроде, во вехде неправильно емя функции - `saveCanvaToLocalStorage` - буква пропущена

2023-11-24 19:16 UTC, Artem-Goldenberg requested changes
Ну да, работает, класс, хоть можно будет нормально тестить теперь
Но тебе там Ваня еще должен написать что-то про то что после обновления он показывает какое-то уведомление об очистке непонятное 
И еще что-то там не помню

2023-11-24 19:16 UTC, Artem-Goldenberg commented on client/templates/main.html
> +      if (!localStorageUsed) {
так зачем переменная localStorageUsed если есть уже editor_info == null

и кстати давайте только в камел кейсе писать

2023-11-25 22:59 UTC, AntoxaBarin commented
При обновлении страницы всё сохраняется, но каждый раз появляется уведомление об очистке модели, наверно, срабатывает какой-то метод, потому что просто так мы не вызываем `clearModel`.

![Screenshot from 2023-11-26 01-57-14](https://github.com/SPbuMinecraft/GraphicalEditorForNN/assets/88805084/ce50b938-a808-44e0-b03b-5ce9d1563064)

2023-11-30 01:39 UTC, Artem-Goldenberg commented
Так, Никита я разобрался почему уведомление показывается при import в пре своем #63 
Посмотрю и ревью сделай как раз. Там суть в том, что import вызывает метод editor.clear, который у нас предопределен так что он кидает уведомления каждый раз. Я там костыльно конечно это убрал но если хочешь сделай по другому 

Но тебе самое главное здесь сделать чтобы никаких запросов к бд не было и чтобы сохраненные модели на вкладке home оставались после перезагрузки

2023-11-30 19:37 UTC, Artem-Goldenberg commented on client/scripts/auth.js
> +    debugger
убери это

2023-11-30 19:37 UTC, Artem-Goldenberg commented on client/templates/main.html
> +
сделай make format

2023-11-30 19:38 UTC, Artem-Goldenberg commented
Еще кстати ты так и не ответил на мой ревью комент выше здесь

2023-12-01 11:17 UTC, Artem-Goldenberg approved these changes

2023-12-01 11:18 UTC, merged