ID-86 (GRA-82): Input selection (without design)
SPbuMinecraft/GraphicalEditorForNN pull request #57
Opened 2023-11-25 22:44 UTC by AntoxaBarin

[ID-86](https://ru.yougile.com/team/b400e1850fe9/#GRA-82)
Этот пр нужен, чтобы вы посмотрели код, вливать в мейн пока не хочу, надо дождаться дизайна. 

Чтоб красиво перетаскивать входы я использовал библиотеку `Sortable.js`. 
Новвоведения находятся в `showLayerInfo`. Если есть вопросы по коду, то задавайте

2023-11-27 12:30 UTC, Artem-Goldenberg requested changes
Чуть подправить
В целом нормально, какая-то библиотека интересная тоже для этой сортировки

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        console.log("selected layer DBID: " + Object.values(editor.getNodeFromId(id)["data"])[0]) // DBID = "database_id;drawflow_id"
да блин, да проще можно, проще 
```js
editor.getNodeFromId(id).data.DBID
```

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        console.log("Connections: " + Object.values(editor.getNodeFromId(id)["data"])[1])
здесь тоже

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        for (var i = 0; i < list_of_connections.length; i++) {
let I

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        if (response == "1") {
че за 1? ну лучше не завязывать на сообщение, лучше смотреть на status
в js есть responce.ok

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        const connections = Object.values(editor.getNodeFromId(id)['data'])[1]
тут тоже убери Object

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        for (let i = 0; i < connections.length; i++) {
`for (let connection of connections) {...}`

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +          console.log("aboba" + i)
дебаг можно убрать

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +          let tmp = addLabelText(connection, connections[i].split(";")[0])
все это сonst

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +      let pathsWithWrittenID = []
непонятно что делает, напиши комент

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        for (let i = 0; i < pathsWithWrittenID.length; i++) {
`for (let path of pathsWith...)`

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        const layer_dbid = Object.values(editor.getNodeFromId(correct_id)['data'])[0]
тут тоже Object не нужен

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        }
можно вынести в функцию + сделать switch а не if else

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        for (let i = 0; i < connections.length; i++) {
опять for (let .. of ..)

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +          let text_for_new_element = document.createTextNode("Input from: " + connections[i].split(";")[0]);
const

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +            console.log('Изменился порядок элементов:');
ну каждый раз то смысл писать

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +                  console.log(sortable_list.childNodes[i].textContent)
это тоже наверное не надо

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +                Parameters: Object.values(editor.getNodeFromId(correct_id)["data"])[2],
опять Object

2023-11-27 12:30 UTC, Artem-Goldenberg commented on client/templates/main.html
> +              document.querySelector("#linear-  inFeatures-parameter").value = layer_parameters[i][1]
это надо?

2023-11-28 09:38 UTC, AntoxaBarin commented on client/templates/main.html
> +        if (response == "1") {
Я исправил это в пр на task132_serverErrorHandling

2023-11-28 09:48 UTC, AntoxaBarin commented on client/templates/main.html
> +      let pathsWithWrittenID = []
При открытии параметров слоя происходит отрисовка id на соединениях. Вот этот массив нужен нам, чтобы отображать эти id

2023-11-28 11:00 UTC, AntoxaBarin commented
Все комменты прочитал, вроде, всё пофиксил. Что-то я мог не менять, потому что это изменено в соседнем pr на обработку ошибок (task132)

2023-11-28 11:11 UTC, Artem-Goldenberg commented on client/templates/main.html
> +      let pathsWithWrittenID = []
я имел ввиду в коде) 
и кстати у меня почему-то даже экран параметров слоя не отображается

2023-11-28 11:12 UTC, Artem-Goldenberg commented
> Все комменты прочитал, вроде, всё пофиксил. Что-то я мог не менять, потому что это изменено в соседнем pr на обработку ошибок (task132)

класс! а здесь что-ли еще старая регистрация? странно, я сейчас запустил у меня не показываются параметры слоя

2023-11-28 11:18 UTC, Artem-Goldenberg requested changes
Одну штуку забыл 
И надо еще мейн влить, а то тут старая регистрация 
И плюс я хз, у меня тут почему то панель выбора параметров вообще не показывается

2023-11-28 11:18 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        for (let i = 0; i < connections.length; i++) {
тут забыл сделать for let of?

2023-11-28 11:21 UTC, AntoxaBarin commented on client/templates/main.html
> +        for (let i = 0; i < connections.length; i++) {
Да, эту забыл поменять. Сейчас еще посмотрю, почему не показываются параметры

2023-11-28 11:28 UTC, AntoxaBarin commented on client/templates/main.html
> +        for (let i = 0; i < connections.length; i++) {
Там короче в метод editor.getNodeFromId передается не распарсенный drawflow id, сейчас переделаю и залью

2023-11-28 12:19 UTC, AntoxaBarin commented
Я нашел 2 проблемы.
1) Не те id в getNodeFromId - просто поменял id
2) При смене порядка входов повторная смена была невозможна. То есть поменяли один раз, а ва второй раз не можем.

Формат соединений внутри слоя: `db_id;drawflow_id` - храним drawflow id в соединениях, чтоб на них отрисовывать id слоев, чтоб было понятно, порядок какого соединения мы меняем. Я после смены порядка входов сохранял в слой соединения в старом формате - `db_id` - просто id из бд. Сейчас я просто сохраняю два массива соединений - первый для бд , второй для сохранения в слое. Форматы у них `db_id` и `db_id;drawflow_id` соответственно.

2023-11-28 16:53 UTC, Artem-Goldenberg commented
> Я нашел 2 проблемы.
> 
> 1. Не те id в getNodeFromId - просто поменял id
> 2. При смене порядка входов повторная смена была невозможна. То есть поменяли один раз, а ва второй раз не можем.
> 
> Формат соединений внутри слоя: `db_id;drawflow_id` - храним drawflow id в соединениях, чтоб на них отрисовывать id слоев, чтоб было понятно, порядок какого соединения мы меняем. Я после смены порядка входов сохранял в слой соединения в старом формате - `db_id` - просто id из бд. Сейчас я просто сохраняю два массива соединений - первый для бд , второй для сохранения в слое. Форматы у них `db_id` и `db_id;drawflow_id` соответственно.

Ну сейчас уже можно оставить, но просто запишу на заметку что зачем мы вообще храним там id, мы же можем хранить их просто объектом `id = {db: int, local: int}`

2023-11-28 16:55 UTC, Artem-Goldenberg approved these changes
ок

2023-11-28 16:56 UTC, Artem-Goldenberg commented
А блин, еще можешь коммент про pathWrittenId написать

2023-11-29 21:54 UTC, merged