ID-132: Server error handling
SPbuMinecraft/GraphicalEditorForNN pull request #59
Opened 2023-11-27 17:17 UTC by AntoxaBarin

Начну с того, что я перенес функции для запросов в отдельный файл `requests.js`. Вроде, всё работает, как надо, запросы отправляются. 
В случае, если мы не можем достучаться до сервера, `sendJson` возвращает failed_request - объект, похожий на response, но в нем всего 2 поля - ok и status. На питоновском сервере есть текст ошибки, но для пользователя он практически всегда неинформативен. Например, при неверном `addLayer` прилетает `No JSON data provided`. 
Пока что на всех ошибках шаблонный текст `Server is not responding now.`. Если что, можно это заменить в некоторых случаях на что-то более содержательное. 

Общая схема обработки ошибок от сервера: перед каждым действием в конструкторе отправляем запрос на сервер: добавление слоя, удаление соединения, очистка модели - всё это происходит только после успешного запроса к БД.
Единственный костыль - `addConnection`. Для него я не смог нормально переопределить библиотечный метод, поэтому я просто удаляю соединение, если сервер не разрешает его добавить. Остальные библиотечные методы (addLayer, deleteLayer, deleteConnection, clearModel) аккуратно переопределены в CustomDrawFlow. Если что-то не так с запросом, то выбрасываем уведомление.

P.S: delay(25) на 342 строке main.html важен. Была проблема - `addLayer` not defined - при самом старте сайта. Это происходило из-за того,  что функция не успела загружаться, но уже вызывалась при выставлении слоев data, output и тд. Этот delay можно ставить хоть на 1 ms, оно и так будет работать. Без него - ошибка

2023-11-27 17:19 UTC, AntoxaBarin commented
Для train, predict, upload выводятся адекватные сообщения по типу `No data was upload` и т.п.

2023-11-27 17:42 UTC, Artem-Goldenberg commented
о кртуо, теперь все должно четко работать 

Я не понял тольк, вот там Артем другой говорил, что он пишет какой-то свой кастовый класс editor, и там предопределяет функции чтобы обрабатывать ошибки, ты это использовал или как?

2023-11-27 17:44 UTC, AntoxaBarin commented
Я не знаю, что он переопределяет, сейчас спрошу у него. Я сам переопределили несколько методов библиотеки и всё

2023-11-27 17:45 UTC, Artem-Goldenberg commented
таааак теперь про твой этот PS, ну вот я знал что у нас либо так уже сделано либо будет так сделано, но это блин вообще жесть какая-то. Уверен это можно по нормальному сделать чтобы не ждать никакой загрузки. Ну я посмотрю

2023-11-27 17:45 UTC, Artem-Goldenberg commented
таааак теперь про твой этот PS, ну вот я знал что у нас либо так уже сделано либо будет так сделано, но это блин вообще жесть какая-то. Уверен это можно по нормальному сделать чтобы не ждать никакой загрузки. Ну я посмотрю

2023-11-27 17:46 UTC, Artem-Goldenberg commented
таааак теперь про твой этот PS, ну вот я знал что у нас либо так уже сделано либо будет так сделано, но это блин вообще жесть какая-то. Уверен это можно по нормальному сделать чтобы не ждать никакой загрузки. Ну я посмотрю

2023-11-27 19:38 UTC, Artem-Goldenberg requested changes
ну это капец, че то у нас Пры какие то большие) по часу смотреть приходится

Ну ладно, ну вообщем так все нормально (правда у меня все равно по моему даже delay 25 не помогает, после экрана регистрации все равно пустая доска) 
Но я там где то написал как мне кажется это можно решить 

Нужно немного зарефакторить так сказать) и посмотри по ссылке на функцию addConnection, это же должно быть как раз то, что надо переопределять

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/scripts/requests.js
> +        return failed_request
Давай failed_request тогда тоже сюда перенесем

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/scripts/requests.js
> +    if (response.status != 200 && response.status != 201) {
Можно писать response.ok, вроде он true на любом 2xx

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/scripts/requests.js
> +    }
тут тоже

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/scripts/requests.js
> +    console.log("Connection added with status: " + response.status)
не ну понятно что там 201, можно connection added и откуда куда
а если фейл то напиши что фейл и тоже откуда куда

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/scripts/requests.js
> +}
ну давай здесь тоже лог сделаем, чтобы было симметрично

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/scripts/requests.js
> +    } else {
тогда console.assert можно убрать

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/scripts/requests.js
> +        const responseText = await response.text()
вынеси тогда это перед if ну и да, там же все таки json у нас теперь приходит, так что response.json()

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/scripts/requests.js
> +            "Failed to predict.\n" + responseText.split(":")[1].split('"')[1],
ну и вот вот этот вот Парсинг тоже можно будет убрать тогда и написать responseJson["error"]

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/scripts/requests.js
> +                responseText.split(":")[1].split('"')[1]
И тут (напишу везде чтобы не пропустить)

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/scripts/requests.js
> +            showBuildNotification(response.ok)
а вот эта штука старое уведомление не покажет?
И если там еще остался старый код от тех уведомлений, то выпили его пж

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
>            if (r === true) {
блин вроде мы об этом не говорили, но можешь еще убрать подтверждения об удалении слоя, а то каждый раз они бесить будут

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +            const layer_dbid = Object.values(this.getNodeFromId(id.split("-")[1])["data"])[0]
В прошлом твоем пре писал как можно убрать этот Object

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
>            if (r === true) {
и var тоже можешь заменить на let пж

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +            const layer_dbid = Object.values(this.getNodeFromId(id.split("-")[1])["data"])[0]
Еще, а че за прикол с этим id, почему оно разделено через - ?

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +              if (response.status == 200 || response.status == 201) {
здесь тоже reponse.ok

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +                errorNotification("Failed to delete layer.\n Server is not responding now.")
Ну, эту строчку можно тогда в константу вынести

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +            if (response.status == 200 || response.status == 201) {
здесь тоже response.ok

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +              super.removeConnection()
Ооо да, хорошо что ты подумал об этом случае когда мы удалил и потом другое быстренькое выбрали 
Но с другой стороны это получается после удаления мы не вернем пользователю его текущий выбор, я же правильно понял?

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +              for (var i = 0; i < listOfConnections.length; i++) {
let let let

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +              let layerParameters = data2.Parameters
const
а точнее вообще не надо, присвой просто там ниже это inplace

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +              console.log(listOfConnections)
ну это можно не логировать уже

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +              listOfConnections.splice(currentElemIndex, 1) // deletes connection from list
что ж время покопаться в старой логике: зачем нам здесь currentElemIndex, мы можем удалить прямо в ифе перед брейком

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +          }
inputs outputs мы решили что не используем, я знаю что это не твоя таска, но раз уж здесь в пре код попался, то хорошее время это убрать)

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +              }
эхх вот поэтому я не люблю js, ну то есть да будет работать, но блин интуитивно вообще непонятно какого хрена у id должен быть статус и если его нет то это число....
давай возвращать из addLayer response как везде, тут просто сделай через response.ok и response.json()

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +                if (response.status == 200 || response.status == 201) {
response.ok

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +      delay(25).then(() => setup())
ага, ну у меня тут проблема что не addLayer не успевает загружаться, а py_server_address. 
Ну это логично потому что он определен здесь, а требуется в requests.js
Предлагаю все такие константы/переменные вынести в отдельный файл и его загружать в первую очередь, по идеи должно решить проблему 
то есть все эти py_server_address user_id  их все вынести отсюда

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
>          console.log(layers_connection)
о классно, что ты ненужные логи подчищаешь, этот тоже можно убрать думаю

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +          if (response.status == 200 || response.status == 201) {
response.ok

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +          }
так вроде функиця так и называется addConnection
https://github.com/jerosoler/Drawflow/blob/300c9efda3bf8820131b3e93ea50cd9b76c892d3/src/drawflow.js#L696

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        let parameters_array = []
ооооо, вот это я понимаю !
Object только надо убрать

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        const connections = Object.values(editor.getNodeFromId(id)["data"])[1]
тут тоже

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +          if (response.status == 200 || response.status == 201) {
response.ok

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        }
вот здесь что за магия происходит ахах? кто такой этот id?

2023-11-27 19:38 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        //const data = getLayerInfoFromDB(id)
ну тут либо раскоментить либо убрать

2023-11-27 22:41 UTC, AntoxaBarin commented on client/templates/main.html
> +            const layer_dbid = Object.values(this.getNodeFromId(id.split("-")[1])["data"])[0]
У drawflow id в таком формате: node-id. Например, node-3

2023-11-27 22:43 UTC, AntoxaBarin commented on client/templates/main.html
> +                errorNotification("Failed to delete layer.\n Server is not responding now.")
Ну там они разные - Failed to delete layer/connection, add layer/connection

2023-11-27 22:49 UTC, AntoxaBarin commented on client/templates/main.html
> +              super.removeConnection()
Как я понял, `removeConnection` удаляет выбранное соединение, ну на которое кликнули. И вот когда мы отправляем запрос на удаление соединения на сервер, у нас это соединение перестает быть выбранным и ` removeConnection` ничего не удаляет.  Поэтому и приходится запоминать соединение, на которое изначально выбрали.

А про текщий выбор я немного не понял

2023-11-27 22:55 UTC, AntoxaBarin commented on client/templates/main.html
> +              }
Да, мне тоже этот код не нравился

2023-11-27 23:10 UTC, AntoxaBarin commented on client/templates/main.html
> +        }
Это короче супер система, которая позволяет принимать как drawflow id, так и распарсенные drawflow id. Дело в том, что при обновлении параметров слоя я могу дважды вызвать этот метод (в случае, если что-то пойдет не так и мне нужно будет вернуть старый параметр слоя). При первом вызове этого метода drawflow id распарсится в норм id типа 2, 10 и т.д. А вот если я второй раз вызову этот метод, то уже с распарсенным drawflow id, но его уже не надо парсить.

2023-11-27 23:17 UTC, AntoxaBarin commented on client/templates/main.html
> +          }
Вот я хотел переопределить метод `addConnection`, но откуда нам знать drawflow id слоев, которые соединяет пользователь? Ну ладно, мы их как-нибудь можем узнать, но в библиотеке соединения строятся в методе `dragEnd(e)`, то есть когда мы ведем соединение к слою мышкой. А метод `addConnection` как сюда привязать - я не придумал. Автор библиотеки использовал `addConnection`, чтобы захардкодить соединения

2023-11-27 23:25 UTC, AntoxaBarin commented
Такс, я, вроде, все комментарии прочел, все изменения сделал. В новом файлике `client/scripts/storage.js` хранятся user_id, python_server_address и прочие константы

2023-11-27 23:27 UTC, AntoxaBarin commented
Неплохо получилось отделить кусочек js кода от main.html. Надо будет еще что-нибудь вытащить в отдельный файлик. Можно всякие уведомления, параметры слоев вынести

2023-11-28 11:30 UTC, Artem-Goldenberg commented on client/scripts/requests.js
> +            showBuildNotification(response.ok)
Это забыл убрать или как?

2023-11-28 11:32 UTC, Artem-Goldenberg commented on client/templates/main.html
> +            const layer_dbid = Object.values(this.getNodeFromId(id.split("-")[1])["data"])[0]
аа понял, тогда все ок

2023-11-28 11:33 UTC, Artem-Goldenberg commented on client/templates/main.html
> +                errorNotification("Failed to delete layer.\n Server is not responding now.")
а ну ладно, пофиг тогда

2023-11-28 11:35 UTC, Artem-Goldenberg commented on client/templates/main.html
> +              super.removeConnection()
а почему когда отправляем на сервер, выбор сбивается? Он типо сам сбивается?

Я то думал просто это пользователь может успеть во время запросы выбрать другое соединение

2023-11-28 11:37 UTC, Artem-Goldenberg commented on client/templates/main.html
> +              let layerParameters = data2.Parameters
layerParameters, присвой ниже просто как data2.Parameters, они же никак не изменяются

2023-11-28 11:46 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        }
А ну ладно, имеет смысл имеет смысл

2023-11-28 11:48 UTC, Artem-Goldenberg commented on client/templates/main.html
> +          }
дааа какая-то костыльная библиотека
Ну ладно вообщем тогда так оставим, главное что все работает

2023-11-28 11:50 UTC, Artem-Goldenberg commented on client/templates/main.html
> +      delay(25).then(() => setup())
Так во, щяс вроде все норм, можно убрать это

2023-11-28 11:52 UTC, Artem-Goldenberg commented on client/scripts/requests.js
> +            showBuildNotification(response.ok)
а не все понял, ты просто переделал

2023-11-28 11:52 UTC, Artem-Goldenberg commented
Да, все вообще классно сделал, все эти var там почистил теперь даже красота какая-то наводится постепенно 
Ну у меня теперь без delay работает, можно убрать это вроде

Посмотри там еще коменты, которые я не закрыл пж

2023-11-28 12:09 UTC, Artem-Goldenberg reviewed
@doejoedoe 
Теперь комит Артема, да все классно, все работает 
Не ну ты круто там конечно принял все решения как этот крестик убрать 
Вижу что это не просто, ты там убираешь библиотечную кнопку, создаешь свою, считаешь где она должна быть...
Ну хорошо, мне все нравится 

Единственно, что ты все как-то сам пытаешься сделать, никого не спрашиваешь, то есть можно было бы на созвонах сказать, что там в библиотеке нельзя отключить кнопку, поэтому ты хочешь сделать так то так то и так то

В данном случае конечно ты все четко сделал, но лучше все равно проговаривать такие неочевидные вещи по коду на созвонах

2023-11-28 12:09 UTC, Artem-Goldenberg commented on client/templates/main.html
> +              if (output_node_name == "target" && input_node_name == "loss") return
ну можно вынести в функцию типа isRemovable или что-то такое раз это в 2 местах используется

2023-11-28 12:09 UTC, Artem-Goldenberg commented on client/templates/main.html
> +        }
а типа он не добавляет соединение если оно уже есть? И тут ты просто не хочешь парится по поводу порядка? 
Ну можно комент по этому поводу написать (в коде)

2023-11-28 18:50 UTC, AntoxaBarin commented on client/templates/main.html
> +              super.removeConnection()
Похоже, что он сам сбивается, я поэтому и добавил `this.connection_selected = selectedConnection`, чтоб соединение удалялось

2023-11-28 18:51 UTC, AntoxaBarin commented on client/templates/main.html
> +      delay(25).then(() => setup())
Да, мы как раз подгружаем в самом начале файлик со всеми функциями, которые запросы отправляют, там и addLayer

2023-11-28 20:08 UTC, AntoxaBarin commented
Все нужные изменения залил последним коммитом

2023-11-30 18:10 UTC, Artem-Goldenberg approved these changes

2023-11-30 19:46 UTC, merged