ID-137: Universal Python Error Handling
SPbuMinecraft/GraphicalEditorForNN pull request #62
Opened 2023-11-28 21:08 UTC by Artem-Goldenberg

Это капец, расписывал тут 2 часа что и как, в итоге все удалилось......

Короче, есть класс теперь Error через него все ошибке теперь кидать нужно, все переписал с использованием его 

Также в `__init__.py` вы можете увидеть, что там я регистрирую обработки для каждого типа ошибки которая может быть 
Они будут вызываться когда в методе API будет выброшена и не отловлена ошибка поэтому все KeyError и вся хрень которую мы раньше в каждом методе отдельно ловили теперь просто попадет в этот обработчик вот, 

Также сделала вариацию csv файлов

2023-12-01 11:15 UTC, lpetrov02 requested changes
Я в каждую строчку не вчитывался, но выглядит здраво.  
Мне вот очень не нравится, что функции для проверок теперь ничего не возвращают, а просто бросают исключение, если что-то не так. По-моему, как-то не очень логично тут смотрятся исключения.  
Но server.py стал красивее, это круто, особенно это общий обработчик ошибок мне понравился))

2023-12-01 11:15 UTC, lpetrov02 commented on py_server/mlcraft/check_dimensions.py
> +def check_dimensions(layers: list[dict]):
Насколько правильно внутри этой функции бросать исключения?  
Мы же тут проверяем, удовлетворяет ли модель требованиям, следовательно, если не удовлетворяет, то это должен быть некий отрицательный результат проверки, а не брошенное исключение.  
Мне вообще кажется странным использование для проверки функции, которая ничего не возвращает, а просто бросает исключение в случае неудачи.  
Но с точки зрения логики программы всё ок конечно)

2023-12-01 11:15 UTC, lpetrov02 commented on py_server/mlcraft/dataset.py
> +    return layer
Выглядит как дублирование кода. Мне кажется, можно это объединить во что-то вроде `get_layers_of_type` - ну название такое конечно нинада, оно кривое, но что-то вроде такого..  
И передавать туда тип параметром

2023-12-01 11:15 UTC, lpetrov02 commented on py_server/mlcraft/dataset.py
> +def extract_train_data(bytes: bytes, model: dict) -> dict:
А у нас эта процедура разве на питоне происходит?

2023-12-01 11:15 UTC, lpetrov02 commented on py_server/mlcraft/dataset.py
> +def extract_predict_data(bytes: bytes, model: dict) -> dict:
То же самое: это точно нужно на питоне?

2023-12-01 11:15 UTC, lpetrov02 commented on py_server/mlcraft/db.py
>              #     return LayersConnectionStatus.DimensionsMismatch
Я вроде бы эти строчки убирал, попробуй ребейз  
(или я забыл их убрать, тогда ладно)

2023-12-01 11:15 UTC, lpetrov02 commented on py_server/tests/test_check_dimensions.py
> +    check_dimensions(layers)
Нехорошо же, когда тест падает с ошибкой просто потому, что не проходит. А тут именно это и случатся - пролетит ошибка снизу и не будет поймана. Мне кажется, это плохо

2023-12-01 11:15 UTC, lpetrov02 commented on py_server/tests/test_check_dimensions.py
> +    check_dimensions(layers)
То же самое про не пойманную ошибку

2023-12-01 13:27 UTC, Artem-Goldenberg commented on py_server/mlcraft/dataset.py
> +    return layer
ну да, хорошая идея

2023-12-01 13:27 UTC, Artem-Goldenberg commented on py_server/mlcraft/dataset.py
> +def extract_train_data(bytes: bytes, model: dict) -> dict:
пока да, пока Макс csv не сделает

2023-12-01 13:27 UTC, Artem-Goldenberg commented on py_server/mlcraft/dataset.py
> +def extract_predict_data(bytes: bytes, model: dict) -> dict:
пока да

2023-12-01 13:28 UTC, Artem-Goldenberg commented on py_server/tests/test_check_dimensions.py
> +    check_dimensions(layers)
любая ошибка которая выброшена в тесте будет отловлена и зарепорчена, это нормальная практика так делать

2023-12-01 13:31 UTC, Artem-Goldenberg commented on py_server/mlcraft/check_dimensions.py
> +def check_dimensions(layers: list[dict]):
Ну с точки зрения Инкапсуляции там, модульной архитектуры ты прав, но здесь нет смысла так запариваться, потому что мы же знаем что мы эту функцию будет вызывать только в методе api, где у нас отлавливаются ошибки 
Можно поменять имя на assert_dimensions_match например

2023-12-01 14:06 UTC, lpetrov02 commented on py_server/mlcraft/check_dimensions.py
> +def check_dimensions(layers: list[dict]):
Да, assert было бы лучше (assert как будто бы ассершн должен кидать, но пофиг)

2023-12-01 14:06 UTC, lpetrov02 commented on py_server/mlcraft/dataset.py
> +def extract_train_data(bytes: bytes, model: dict) -> dict:
Ок пон

2023-12-01 14:08 UTC, lpetrov02 commented on py_server/tests/test_check_dimensions.py
> +    check_dimensions(layers)
Нуу как скажешь

2023-12-01 14:16 UTC, Artem-Goldenberg commented on py_server/mlcraft/check_dimensions.py
> +def check_dimensions(layers: list[dict]):
что за асершн?

2023-12-02 14:44 UTC, lpetrov02 commented on py_server/mlcraft/check_dimensions.py
> +def check_dimensions(layers: list[dict]):
Мб это в питоне только есть  
Забей))

2023-12-02 14:46 UTC, lpetrov02 approved these changes
Ну как договаривались - не душним слишком сильно))  
Вот галка, вроде всё круто

2023-12-02 17:55 UTC, merged