ID-89: Csv working system in C++ server
SPbuMinecraft/GraphicalEditorForNN pull request #64
Opened 2023-11-30 18:39 UTC by MaxVorosh

[ID-89](https://ru.yougile.com/team/b400e1850fe9/#GRA-89)

Для работы необходима папка model_data, в которой две папки - data и predict. Было бы неплохо, чтобы они создавались в Makefile

2023-12-01 11:51 UTC, lpetrov02 requested changes
Выглядит классно, поправь только там некоторые штучки из тех, что я написал

2023-12-01 11:51 UTC, lpetrov02 commented on server/api/CsvLoader.cpp
> +}
< No newline at the end of file >

2023-12-01 11:51 UTC, lpetrov02 commented on server/api/CsvLoader.h
> +};
< No newline at the end of file >

2023-12-01 11:51 UTC, lpetrov02 commented on server/api/CsvLoader.h
> +class CsvLoader {
А зачем на класс, если он без поле и всего с одним методом?  
Мб функцию лучше?

2023-12-01 11:51 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +    // All data goes to every data layer. Should be changed?
Пока что пофиг  
Вряд ли мы дойдём до многих входов, особенно в ближайшее время

2023-12-01 11:51 UTC, lpetrov02 commented on server/api/GraphBuilder.h
> +    void OverviewLayers(const crow::json::rvalue& layers, const std::vector<std::vector<float>> data,
`data` не по ссылке?

2023-12-01 11:51 UTC, lpetrov02 commented on server/api/GraphBuilder.h
> +                        std::unordered_map<int, std::vector<float>>& data_dicts);
Строчку между методами)

2023-12-01 11:51 UTC, lpetrov02 commented on server/api/Parser.cpp
> +void ParseCsvData(const std::vector<std::vector<float>> data, std::vector<float>& instances, std::vector<float>& answers) {
Нейминг такой, как будто бы предполагается какая-то работа непосредственно с csv, а её нет((  
Но это мелочи, вопрос опять про `data` не по ссылке

2023-12-01 11:51 UTC, lpetrov02 commented on server/api/Parser.cpp
> +        answers.push_back(instance.back());
Вообще ответ может быть не одним числом, а массивичком, но давай пока на это забьём

2023-12-01 11:51 UTC, lpetrov02 commented on server/api/Parser.cpp
> +            instances.push_back(instance[i]);
Тут, кажется, если выделить заранее достаточно памяти (`instances.reserve(...)`), то можно как-то разом скопировать (что-то типа `std::memcpy`)  
Но не факт, что стоит гнаться за этой микро-оптимизацией, вряд ли там большая разница будет

2023-12-01 11:51 UTC, lpetrov02 commented on server/tests/CsvLoaderTests.cpp
> +#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
За тесты лайк

2023-12-01 11:51 UTC, lpetrov02 commented on server/tests/CsvLoaderTests.cpp
> +}
< No new line at the end of file >

2023-12-01 11:51 UTC, lpetrov02 commented on server/tests/GraphTests.cpp
>  }
< No newline at the end of file >  
Это, конечно, не то, что ты менял, я тоже что ли этим грешу жесть..

2023-12-01 11:51 UTC, lpetrov02 commented
> [ID-89](https://ru.yougile.com/team/b400e1850fe9/#GRA-89)
> 
> Для работы необходима папка model_data, в которой две папки - data и predict. Было бы неплохо, чтобы они создавались в Makefile
> 
> И это только (!) на плюсах. Нужно ещё поменять соответствующие запросы на питоне и на фронте

Это запрос к @Artem-Goldenberg ?

2023-12-01 11:58 UTC, MaxVorosh commented
> > [ID-89](https://ru.yougile.com/team/b400e1850fe9/#GRA-89)
> > Для работы необходима папка model_data, в которой две папки - data и predict. Было бы неплохо, чтобы они создавались в Makefile
> > И это только (!) на плюсах. Нужно ещё поменять соответствующие запросы на питоне и на фронте
> 
> Это запрос к @Artem-Goldenberg ?

В первую очередь - да. Но если кто-то ещё может это сделать - не вопрос

2023-12-01 12:04 UTC, MaxVorosh commented on server/api/CsvLoader.h
> +class CsvLoader {
Нам в будущем может понадобиться какие-то другие операции с csv делать. Как я понял, csv, который будет в архиве с котиками, нужно чуть по-другому обрабатывать

2023-12-01 15:08 UTC, Artem-Goldenberg commented
да окей сделаю без проблем

2023-12-02 14:41 UTC, lpetrov02 approved these changes
Вот тебе галка!
Только перед тем как вливать сделай ссылку, где надо, ну и подумай, не стоит ли класс на неймспейс заменить

2023-12-02 14:41 UTC, lpetrov02 commented on server/api/CsvLoader.h
> +class CsvLoader {
Ну пока что класс используется чисто как `namespace`. Если методы не будут пользоваться общими полями, то, кажется, лучше `namespace` сделать. Если нужны общие поля, то оставляем класс, вопросов нет

2023-12-02 14:41 UTC, lpetrov02 commented on server/api/GraphBuilder.cpp
> +             std::vector<std::vector<float>> data,
Блин сорян, что сразу не заметил, но тут вроде бы тоже константную ссылку лучше, `data` же не меняется нигде  
Вот как в `OverviewLayers` -  так же

2023-12-02 18:44 UTC, Maxon081102 approved these changes

2023-12-03 20:01 UTC, Artem-Goldenberg commented
Не ну Макс если хочешь, можешь вливать свой, я потом в свой замержу тогда, так даже удобнее будет

2023-12-03 20:02 UTC, Artem-Goldenberg approved these changes

2023-12-03 20:02 UTC, Artem-Goldenberg commented on server/api/CsvLoader.h
> +class CsvLoader {
Леня, ПОФИГ, не забываем. Можно оставить, можно сделать namespace с отдельными функциями но это в принципе тоже самое

2023-12-03 20:02 UTC, Artem-Goldenberg commented on server/api/CsvLoader.cpp
> +        boost::split(content, line, boost::is_any_of(","));
единственное где используется boost это здесь? Так есть вроде такие стандартные функции, не? а то надо будет все время путь к кусту прописывать

2023-12-04 17:04 UTC, merged