GRA-181: zip upload
SPbuMinecraft/GraphicalEditorForNN pull request #75
Opened 2023-12-14 15:18 UTC by MaxVorosh

[GRA-181](https://ru.yougile.com/team/b400e1850fe9/#GRA-181)

2023-12-14 17:02 UTC, MaxVorosh commented
Теперь мы умеем загружать zip файлы на train и png файлы на предикт. Остаётся проблема с загрузкой больших файлов. Но возможно, это ограничение ОС. 
Изменение train и predict сделано максимально просто, не используя многие возможности DataLoader, поскольку я абсолютно не понимаю наш аллокатор. Это нужно будет поменять в дальнейшем. Пока что, это просто способ прочитать данные из файла.
Я не проверял тренировку нейросети на zip, поскольку я не знаю, как сделать модель, которая сможет обрабатывать это. Что точно работает: загрузка zip и csv на train, png и zip на predict. В случае с csv я протестировал и train с predict.
Сейчас не проходят тесты, поскольку нужно добавить установку библиотеки libzip. В makefile я её добавил, но на самой машине, где крутятся тесты, её нет. Если кто знает, как это сделать, добавьте пожалуйста

2023-12-15 06:44 UTC, lpetrov02 requested changes
Такс, в целом всё круто, но нужно немного реорганизовать.   
В принципе я увидел, как работает даталоадер, могу дальше подхватить, подправить комменты, они такие, польше по ML.  
К тому же, ты ещё вечером пр залил, я только сейчас посмотрел)

2023-12-15 06:44 UTC, lpetrov02 commented on server/api/server.cpp
> +    }
Получается, `path` у нас исходно без расширения. Звучит как место, где можно запутаться и выстрелить себе в ногу  
Но пока наверно можно оставить, если работает, то, как говорится, ПОФИГ!!

2023-12-15 06:44 UTC, lpetrov02 commented on server/api/server.cpp
> +
Цикл по-хорошему должен быть внутри того, который идёт по эпохам. Суть в том, что одна эпоха - это следующая штучка: мы из даталоадера подгружаем батч (в нашем случае - записываем его в дату), потом один раз гоняем forward-backward, потом чето там с метриками логгируем (это на мне), а потом подгружаем новый батч, делаем ChangeInputData (как в предикте, только надо ещё таргеты поменять) - и тд, пока не кончатся батчи. А потом новая эпоха

2023-12-15 06:44 UTC, lpetrov02 commented on server/api/server.cpp
> +    }
Ну вот тут, если предиктим по одной штуке, то норм.  
Если бы могли по много штуков делать, то тут тоже нужно было бы цикл по даталоадеру сделать. Но пока что ПОФИГ

2023-12-15 06:44 UTC, lpetrov02 commented on server/api/server.cpp
> +        if (file_type == 0) {
Тут, чтобы не было *magic numbers*, лучше сделать енамчик для расширений. Не критично, но если получится, то будет неплохо

2023-12-15 06:48 UTC, MaxVorosh commented on server/api/server.cpp
> +        if (file_type == 0) {
Енамчик есть. Но мы как-то это должны передать в адресе запроса. А там только int можно. Артём сказал, к тому же, что в своём пр-е он будет передавать это в header-е запроса, поэтому, думаю, можно так оставить

2023-12-15 06:54 UTC, lpetrov02 commented on server/api/server.cpp
> +        if (file_type == 0) {
А енам с интом сравнить нельзя?  
Типа `if (file_type == FileType::Csv)`?

2023-12-15 06:58 UTC, MaxVorosh commented on server/api/server.cpp
> +        if (file_type == 0) {
Я как-то даже не смотрел. Но опять же, в будущем (в пр-е Артёма) тут будет проверка Content-type из header,так что не думаю, что нужно сейчас много внимания этому уделять

2023-12-24 18:14 UTC, closed without merging