Input selection bug fix
SPbuMinecraft/GraphicalEditorForNN pull request #79
Opened 2023-12-18 12:54 UTC by AntoxaBarin

Выбор входов не отображался из-за изменения формата строки, сыпались ошибки, и окно параметров не открывалось.

2023-12-18 23:09 UTC, Artem-Goldenberg commented
Уфф ну надо пофиксить конфликты) Ну там я так понимаю просто принимаешь то что есть, хотя все равно смотри на всякий случай чтоб свое не затереть

2023-12-19 09:21 UTC, AntoxaBarin commented
Я решил конфликты, надо проверить, что я там ничего лишнего не убрал

2023-12-19 17:18 UTC, Artem-Goldenberg requested changes
Да, убери тут вот это и можно вливать

2023-12-19 17:18 UTC, Artem-Goldenberg commented on server/core/Shape.cpp
> +    for (int i = 4 - dimsCount; i < 4; i++) {
вот это надо оставить как было, это мы специально поменяли

2023-12-19 17:18 UTC, Artem-Goldenberg commented on server/core/Operation.h
> +    }
вот это вроде договорились что тоже не надо

2023-12-19 17:18 UTC, Artem-Goldenberg commented on server/api/server.cpp
> +
Это тоже можешь пока убрать, оно в моем пре есть

2023-12-19 17:24 UTC, Artem-Goldenberg commented
Кстати еще остался баг с тем, что удаляешь слой, а во входах он не удаляется

2023-12-19 23:44 UTC, AntoxaBarin commented
Починил этот баг, утром посмотрю комментарии выше

2023-12-20 17:42 UTC, Artem-Goldenberg commented
Все хорошо, можно вливать

2023-12-20 17:42 UTC, Artem-Goldenberg approved these changes

2023-12-21 17:53 UTC, merged